openapi: "3.0.0"
info:
  version: 2.0.0
  title: Lichess.org API reference
  x-logo:
    url: https://lichess1.org/assets/logo/lichess-pad12.svg
    backgroundColor: #ffffff
  description: "\n\n# Introduction\nWelcome to the reference for the Lichess API! Lichess is free/libre, open-source chess server powered by volunteers and donations.\n\n\
  \ - Get help in the [lichess developers discord channel](https://discord.gg/pw6Efvk),\
  \ or in the #lichess IRC channel on freenode.\n\
  \ - [Contribute to this documentation on Github](https://github.com/lichess-org/api).\n\
  \ - Check out [lichess widgets to embed in your website](https://lichess.org/developers).\n\
  \ - [Download all Lichess rated games](https://database.lichess.org/)\n\
  \ - [Download all Lichess puzzles with themes, ratings and votes](https://database.lichess.org/#puzzles)\n\
  \n## Endpoint\n\
  \ All requests go to `https://lichess.org`.\n\
  \n## Clients\n\
  - [Python general API](https://github.com/rhgrant10/berserk)\n\
  - [Python general API - async](https://pypi.org/project/async-lichess-sdk)\n\
  - [Python Lichess Bot](https://github.com/careless25/lichess-bot)\n\
  - [Python Board API for Certabo](https://github.com/haklein/certabo-lichess)\n\
  \n## Rate limiting\n\
  \ All requests are rate limited using various strategies,\
  \ to ensure the API remains responsive for everyone.\n\
  \ Only make one request at a time.\n\
  \ If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429),\
  \ please wait a full minute before resuming API usage."
servers:
  - url: https://lichess.org
tags:
- name: Account
  description: |
    Read and write account informations and preferences.
    https://lichess.org/account/preferences/game-display
- name: Users
  description: |
    Access registered users on Lichess.
    https://lichess.org/player
- name: Relations
  description: |
    Access relations between users.
- name: Games
  description: |
    Access games played on Lichess.
    https://lichess.org/games
- name: Puzzles
  description: "Access Lichess puzzle history and dashboard. https://lichess.org/training\n\n
  \ Our collection of puzzles is in the public domain, you can [download it here](https://database.lichess.org/#puzzles).\n\n
  \ For a list of our puzzle themes with their description, check out the [theme translation file](https://github.com/ornicar/lila/blob/master/translation/source/puzzleTheme.xml)."
- name: Teams
  description: |
    Access and manage Lichess teams and their members.
    https://lichess.org/team
- name: Board
  description: "Play on Lichess with physical boards and third-party clients.\n
  \ Works with normal Lichess accounts. Engine play or assistance is forbidden.\n\n\
  \n### Features\n\
  \ - [Stream incoming chess moves](#operation/boardGameStream)\n\
  \ - [Play chess moves](#operation/boardGameMove)\n\
  \ - [Read](#operation/boardGameStream) and [write](#operation/boardGameChat) in the player and spectator chats\n\
  \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges\n\
  \ - [Abort](#operation/boardGameAbort) and [resign](#operation/boardGameResign) games\n\
  \ - Compatible with normal Lichess accounts\n\n
  \n### Restrictions\n\
  \ - Engine assistance is strictly forbidden\n\
  \ - Time controls: [Rapid, Classical and Correspondence](https://lichess.org/faq#time-controls) only\n\
  \n### Links\n\
  \ - [Announcement](https://lichess.org/blog/XlRW5REAAB8AUJJ-/welcome-lichess-boards)\n\
  \ - [Certabo support](https://github.com/haklein/certabo-lichess)\n\
  \ - [Lichs (play from command-line)](https://github.com/Cqsi/lichs)"
- name: Bot
  description: "Play on Lichess as a bot. Allows engine play.\n
  \ Read the [blog post announcement of lichess bots](https://lichess.org/blog/WvDNticAAMu_mHKP/welcome-lichess-bots).\n\n
  \ Only works with [Bot accounts](#operation/botAccountUpgrade).\n\n\
  \n### Features\n\
  \ - [Stream incoming chess moves](#operation/botGameStream)\n\
  \ - [Play chess moves](#operation/botGameMove)\n\
  \ - [Read](#operation/botGameStream) and [write](#operation/botGameChat) in the player and spectator chats\n\
  \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges\n\
  \ - [Abort](#operation/botGameAbort) and [resign](#operation/botGameResign) games\n\
  \ - Engine assistance is allowed\n\
  \n### Restrictions\n\
  \ - Bots can only play challenge games:  pools and tournaments are off-limits\n\
  \ - Bots cannot play UltraBullet (¼+0) because it requires making too many requests. But 0+1 and ½+0 are allowed.\n\
  \n### Integrations\n\
  \ - [Python3 lichess-bot](https://github.com/careless25/lichess-bot) (official)\n\
  \ - [JavaScript bot-o-tron](https://github.com/tailuge/bot-o-tron)\n\
  \ - [Golang lichess-bot](https://github.com/dolegi/lichess-bot)\n\
  \ - Yours? Please make [an issue or pull request](https://github.com/lichess-org/api).\n\
  \n### Links\n\
  \ - [Announcement](https://lichess.org/blog/WvDNticAAMu_mHKP/welcome-lichess-bots)\n\
  \ - Join the [Lichess Bots team](https://lichess.org/team/lichess-bots) with your bot account\n\
  \ - [Get help in the discord channel](https://discord.gg/quwueFd)\n\
  \ - Watch [Lichess Bot TV](https://lichess.org/tv/bot)"
- name: Challenges
  description: |
    Send and receive challenges to play.

    To create a lot of challenges, consider [bulk pairing](#operation/bulkPairingCreate) instead.
- name: Bulk pairings
  description: |
    Create many games for other players.

    These endpoints are intended for tournament organisers.
- name: Arena tournaments
  description: |
    Access Arena tournaments played on Lichess.
    [Official Arena tournaments](https://lichess.org/tournament) are maintained by Lichess,
    but you can [create your own Arena tournaments](https://lichess.org/tournament/new) as well.
- name: Swiss tournaments
  description: |
    Access Swiss tournaments played on Lichess.
    [Read more about Swiss tournaments.](https://lichess.org/swiss).
- name: Simuls
  description: |
    Access simuls played on Lichess.
    https://lichess.org/simul
- name: Studies
  description: |
    Access Lichess studies.
    https://lichess.org/study
- name: Messaging
  description: |
    Private messages with other players.
    https://lichess.org/inbox
- name: Broadcasts
  description: |
    Relay chess events on Lichess.
    [Official broadcasts](https://lichess.org/broadcast) are maintained by Lichess,
    but you can [create your own broadcasts](https://lichess.org/broadcast/new) to cover any live game or chess event.
    You will need to publish PGN on a public URL so that Lichess can pull updates from it.
    Alternatively, you can push PGN updates to Lichess using this API.
- name: Analysis
  description: |
    Access Lichess cloud evaluations database.
    https://lichess.org/analysis
- name: Opening Explorer
  description: |
    Lookup positions from the [Lichess opening explorer](https://lichess.org/analysis#explorer).

    **The endpoint hostname is not lichess.org but explorer.lichess.ovh.**
- name: Tablebase
  description: |
    Lookup positions from the [Lichess tablebase server](https://lichess.org/blog/W3WeMyQAACQAdfAL/7-piece-syzygy-tablebases-are-complete).

    **The endpoint hostname is not lichess.org but tablebase.lichess.ovh.**
- name: OAuth
  description: |
    Requests taking advantage of OAuth authentication.
    https://lichess.org/account/oauth/app
paths:
  /api/users/status:
    get:
      operationId: apiUsersStatus
      summary: Get real-time users status
      description: |
        Read the `online`, `playing` and `streaming` flags of several users.

        This API is very fast and cheap on lichess side.
        So you can call it quite often (like once every 5 seconds).

        Use it to track players and know when they're connected on lichess and playing games.
      tags:
        - Users
      security:
        - None: []
  /player:
    get:
      operationId: player
      summary: Get all top 10
      tags:
        - Users
      security:
        - SameOrigin: []
      description: |
        Get the top 10 players for each speed and variant.

        See https://lichess.org/player.
  /player/top/{nb}/{perfType}:
    get:
      operationId: playerTopNbPerfType
      summary: Get one leaderboard
      tags:
        - Users
      security:
        - SameOrigin: []
      description: |
        Get the leaderboard for a single speed or variant (a.k.a. `perfType`).
        There is no leaderboard for correspondence or puzzles.

        See https://lichess.org/player/top/200/bullet.
  /api/user/{username}:
    get:
      operationId: apiUser
      summary: Get user public data
      description: |
        Read public data of a user.
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/rating-history:
    get:
      operationId: apiUserRatingHistory
      summary: Get rating history of a user
      description: |
        Read rating history of a user, for all perf types.
        There is at most one entry per day.
        Format of an entry is `[year, month, day, rating]`.
        `month` starts at zero (January).
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/activity:
    get:
      operationId: apiUserActivity
      summary: Get user activity
      description: |
        Read data to generate the activity feed of a user.
      tags:
        - Users
      security:
        - None: []
  /api/puzzle/activity:
    get:
      operationId: apiPuzzleActivity
      summary: Get your puzzle activity
      description: |
        Download your puzzle activity in [ndjson](http://ndjson.org/) format.

        Puzzle activity is sorted by reverse chronological order (most recent first)

        We recommend streaming the response, for it can be very long.
      tags:
        - Puzzles
        - OAuth
      security:
        - OAuth2: ["puzzle:read"]
  /api/puzzle/dashboard/{days}:
    get:
      operationId: apiPuzzleDashboard
      summary: Get your puzzle dashboard
      description: |
        Download your [puzzle dashboard](https://lichess.org/training/dashboard/30/dashboard) as JSON.

        Also includes all puzzle themes played, with aggregated results.

        Allows re-creating the [improvement/strengths](https://lichess.org/training/dashboard/30/improvementAreas) interfaces.
      tags:
        - Puzzles
        - OAuth
      security:
        - OAuth2: ["puzzle:read"]
  /api/storm/dashboard/{username}:
    get:
      operationId: apiStormDashboard
      summary: Get the storm dashboard of a player
      description: |
        Download the [storm dashboard](https://lichess.org/storm/dashboard/mrbasso) of any player as JSON.

        Contains the aggregated highscores, and the history of storm runs aggregated by days.

        Use `?days=0` if you only care about the highscores.
      tags:
        - Puzzles
      security:
        - None: []
  /api/users:
    post:
      operationId: apiUsers
      summary: Get users by ID
      tags:
        - Users
      security:
        - None: []
      description: |
        Get up to 300 users by their IDs. Users are returned in the order same order as the IDs.

        The method is `POST` so a longer list of IDs can be sent in the request body.
  /api/account:
    get:
      operationId: accountMe
      summary: Get my profile
      description: |
        Public informations about the logged in user.
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: []
  /api/account/email:
    get:
      operationId: accountEmail
      summary: Get my email address
      description: |
        Read the email address of the logged in user.
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["email:read"]
  /api/account/preferences:
    get:
      operationId: account
      summary: Get my preferences
      description: |
        Read the preferences of the logged in user.

        - https://lichess.org/account/preferences/game-display
        - https://github.com/ornicar/lila/blob/master/modules/pref/src/main/Pref.scala
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:read"]
  /api/account/kid:
    get:
      operationId: accountKid
      summary: Get my kid mode status
      description: |
        Read the kid mode status of the logged in user.

        - https://lichess.org/account/kid
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:read"]
    post:
      operationId: accountKidPost
      summary: Set my kid mode status
      description: |
        Set the kid mode status of the logged in user.

        - https://lichess.org/account/kid
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:write"]
  /game/export/{gameId}:
    get:
      operationId: gamePgn
      summary: Export one game
      description: |
        Download one game in either PGN or JSON format.

        Ongoing games have their last 3 moves omitted, after move 5.
      tags:
        - Games
      security:
        - None: []
  /api/user/{username}/current-game:
    get:
      operationId: apiUserCurrentGame
      summary: Export ongoing game of a user
      description: |
        Download the ongoing game, or the last game played, of a user.
        Available in either PGN or JSON format.
        If the game is ongoing, the 3 last moves are omitted.
      tags:
        - Games
      security:
        - None: []
  /api/games/user/{username}:
    get:
      operationId: apiGamesUser
      summary: Export games of a user
      description: |
        Download all games of any user in PGN or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (most recent first)

        We recommend streaming the response, for it can be very long.
        https://lichess.org/@/german11 for instance has more than 320,000 games.

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Authentication) request: 30 games per second
          - Authenticated, downloading your own games: 60 games per second
      tags:
        - Games
        - OAuth
      security:
        - None: []
        - OAuth2: []
  /games/export/_ids:
    post:
      operationId: gamesExportIds
      summary: Export games by IDs
      description: |
        Download games by IDs in PGN or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (most recent first)

        The method is `POST` so a longer list of IDs can be sent in the request body.

        300 IDs can be submitted.

        Ongoing games have their last 3 moves omitted, after move 5.
      tags:
        - Games
      security:
        - SameOrigin: []
  /api/stream/games-by-users:
    post:
      operationId: gamesByUsers
      summary: Stream current games
      description: |
        Stream the games played between a list of users, in real time.
        Only games where **both players** are part of the list are included.

        Maximum number of users: 300.

        **Games are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.

        The method is `POST` so a longer list of IDs can be sent in the request body.
      tags:
        - Games
      security:
        - None: []
  /api/account/playing:
    get:
      operationId: apiAccountPlaying
      summary: Get ongoing games
      description: |
        Get the ongoing games of the current user.
        Real-time and correspondence games are included.
        The most urgent games are listed first.
      tags:
        - Games
        - OAuth
      security:
        - OAuth2: []
  /api/tv/channels:
    get:
      operationId: tvChannels
      summary: Get current TV games
      description: |
        Get basic info about the best games being played for each speed and variant,
        but also computer games and bot games.

        See [lichess.org/tv](https://lichess.org/tv).
      tags:
        - Games
      security:
        - None: []
  /tv/feed:
    get:
      operationId: tvFeed
      summary: Stream current TV game
      description: |
        Stream positions and moves of the current [TV game](https://lichess.org/tv) in [ndjson](http://ndjson.org/).
        A summary of the game is sent as a first message, and when the featured game changes.

        Try it with `curl https://lichess.org/tv/feed`.
      tags:
        - Games
      security:
        - SameOrigin: []
  /api/import:
    post:
      operationId: gameImport
      summary: Import one game
      description: |
        Import a game from PGN. See https://lichess.org/paste.

        Rate limiting: 200 games per hour for OAuth requests, 100 games per hour for anonymous requests.

        To broadcast ongoing games, consider [pushing to a broadcast instead](#operation/broadcastPush).
      tags:
        - Games
        - OAuth
      security:
        - None: []
        - OAuth2: []
  /api/tournament:
    get:
      operationId: apiTournament
      summary: Get current tournaments
      description: |
        Get recently finished, ongoing, and upcoming tournaments.

        This API is used to display the [Lichess tournament schedule](https://lichess.org/tournament).
      tags:
        - "Arena tournaments"
      security:
        - None: []
    post:
      operationId: apiTournamentPost
      summary: Create a new Arena tournament
      description: |
        Create a public or private Arena tournament.

        This endpoint mirrors the form on https://lichess.org/tournament/new.

        You can create up to 12 public tournaments per day, or 24 private tournaments.

        A team battle can be created by specifying the `teambBattleByTeam` argument.
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}:
    get:
      operationId: tournament
      summary: Get info about an Arena tournament
      description: |
        Get detailed info about recently finished, current, or upcoming tournament's duels, player standings, and other info.
      tags:
        - "Arena tournaments"
      security:
        - None: []
    post:
      operationId: apiTournamentUpdate
      summary: Update an Arena tournament
      description: |
        Update an Arena tournament.

        Be mindful not to make important changes to ongoing tournaments.

        Can be used to update a team battle.
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/team-battle/{id}:
      post:
        operationId: apiTournamentTeamBattlePost
        summary: Update a team battle
        description: |
          Set the teams and number of leaders of a team battle.

          To update the other attributes of a team battle, use the [tournament update endpoint](#operation/apiTournamentUpdate).
        tags:
          - "Arena tournaments"
        security:
          - OAuth2: ["tournament:write"]
  /api/tournament/{id}/games:
    get:
      operationId: gamesByTournament
      summary: Export games of an Arena tournament
      description: |
        Download games of a tournament in PGN or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (most recent first)
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/results:
    get:
      operationId: resultsByTournament
      summary: Get results of an Arena tournament
      description: |
        Players of an Arena tournament, with their score and performance, sorted by rank (best first).

        **Players are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/teams:
    get:
      operationId: teamsByTournament
      summary: Get team standing of a team battle
      description: |
        Teams of a team battle tournament, with top players, sorted by rank (best first).
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/user/{username}/tournament/created:
    get:
      operationId: apiUserNameTournamentCreated
      summary: Get tournaments created by a user
      description: |
        Get all tournaments created by a given user.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        **Tournaments are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/swiss/new/{teamId}:
    post:
      operationId: apiSwissNew
      summary: Create a new Swiss tournament
      description: |
        Create a Swiss tournament for your team.

        This endpoint mirrors the Swiss tournament form from your team pagee.

        You can create up to 12 tournaments per day.
      tags:
        - "Swiss tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /swiss/{id}.trf:
    get:
      operationId: swissTrf
      summary: Export TRF of a Swiss tournament
      description: |
        Download a tournament in the Tournament Report File format, the FIDE standard.

        Documentation: https://www.fide.com/FIDE/handbook/C04Annex2_TRF16.pdf

        Example: https://lichess.org/swiss/j8rtJ5GL.trf
      tags:
        - "Swiss tournaments"
      security:
        - None: []
  /api/swiss/{id}/games:
    get:
      operationId: gamesBySwiss
      summary: Export games of a Swiss tournament
      description: |
        Download games of a swiss tournament in PGN or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (last round first)
      tags:
        - "Swiss tournaments"
      security:
        - None: []
  /api/swiss/{id}/results:
    get:
      operationId: resultsBySwiss
      summary: Get results of a swiss tournament
      description: |
        Players of a swiss tournament, with their score and performance, sorted by rank (best first).

        **Players are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      tags:
        - "Swiss tournaments"
      security:
        - None: []
  /api/team/{teamId}/swiss:
    get:
      operationId: apiTeamSwiss
      summary: Get team swiss tournaments
      description: |
        Get all swiss tournaments of a team.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        **Tournaments are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Teams
        - "Swiss tournaments"
      security:
        - None: []
  /study/{studyId}/{chapterId}.pgn:
    get:
      operationId: studyChapterPgn
      summary: Export one study chapter
      description: |
        Download one study chapter in PGN format.
      tags:
        - Studies
      security:
        - SameOrigin: []
  /study/{studyId}.pgn:
    get:
      operationId: studyChapterPgn
      summary: Export all chapters
      description: |
        Download all chapters of a study in PGN format.
      tags:
        - Studies
      security:
        - SameOrigin: []
  /api/broadcast:
    get:
      operationId: broadcastIndex
      summary: Get official broadcasts
      description: |
        Get all incoming, ongoing, and finished official broadcasts.
        The broadcasts are sorted by start date, most recent first.

        **Broadcasts are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Broadcasts
  /broadcast/new:
    post:
      operationId: broadcastCreate
      summary: Create a broadcast
      description: |
        Create a new broadcast to relay external games.
        This endpoint accepts the same form data as the [web form](https://lichess.org/broadcast/new).
      tags:
        - Broadcasts
        - OAuth
      security:
        - OAuth2: ["study:write"]
  /broadcast/{slug}/{broadcastId}:
    get:
      operationId: broadcastGet
      summary: Get your broadcast
      description: |
        Get information about a broadcast that you created.
        You will need it if you want to update that broadcast.
      tags:
        - Broadcasts
        - OAuth
      security:
        - OAuth2: ["study:read"]
          SameOrigin: []
  /broadcast/{slug}/{broadcastId}/edit:
      post:
        operationId: broadcastUpdate
        summary: Update your broadcast
        description: |
          Update information about a broadcast that you created.
          This endpoint accepts the same form data as the web form.
          All fields must be populated with data. Missing fields will override the broadcast with empty data.
          For instance, if you omit `startDate`, then any pre-existing start date will be removed.
        tags:
          - Broadcasts
          - OAuth
        security:
          - OAuth2: ["study:write"]
  /broadcast/{slug}/{broadcastId}/push:
    post:
      operationId: broadcastPush
      summary: Push PGN to your broadcast
      description: |
        Update your broadcast with new PGN.
        Only for broadcast without a source URL.
      tags:
        - Broadcasts
        - OAuth
      security:
        - OAuth2: ["study:write"]
          SameOrigin: []
  /api/simul:
    get:
      operationId: apiSimul
      summary: Get current simuls
      description: |
        Get recently finished, ongoing, and upcoming simuls.
      tags:
        - Simuls
      security:
        - None: []
  /api/team/{teamId}:
    get:
      operationId: teamShow
      summary: Get a single team
      description: Infos about a team
      tags:
        - Teams
      security:
        - None: []
  /api/team/all:
    get:
      operationId: teamAll
      summary: Get popular teams
      description: |
        Paginator of the most popular teams.
      tags:
        - Teams
      security:
        - None: []
  /api/team/of/{username}:
    get:
      operationId: teamOfUsername
      summary: Teams of a player
      description: |
        All the teams a player is a member of.
      tags:
        - Teams
      security:
        - None: []
  /api/team/search:
    get:
      operationId: teamSearch
      summary: Search teams
      description: |
        Paginator of team search results for a keyword.
      tags:
        - Teams
      security:
        - None: []
  /api/team/{teamId}/users:
    get:
      operationId: teamIdUsers
      summary: Get members of a team
      description: |
        Members are sorted by reverse chronological order of joining the team (most recent first).

        **Members are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Users
        - Teams
      security:
        - None: []
  /api/team/{teamId}/arena:
    get:
      operationId: apiTeamArena
      summary: Get team Arena tournaments
      description: |
        Get all Arena tournaments relevant to a team.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        **Tournaments are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Teams
        - "Arena tournaments"
      security:
        - None: []
  /team/{teamId}/join:
    post:
      operationId: teamIdJoin
      summary: Join a team
      description: |
        Join a team.
        If the team join policy requires a confirmation,
        and the team owner is not the oAuth app owner,
        and the `message` field is not set,
        then the call fails with `403 Forbidden`.
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/quit:
    post:
      operationId: teamIdQuit
      summary: Leave a team
      description: |
        Leave a team.
        - https://lichess.org/team
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/kick/{userId}:
    post:
      operationId: teamIdKickUserId
      summary: Kick a user from your team
      description: |
        Kick a member out of one of your teams.
        - https://lichess.org/team
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/pm-all:
    post:
      operationId: teamIdPmAll
      summary: Message all members
      description: |
        Send a private message to all members of a team.
        You must own the team.
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
  /streamer/live:
    get:
      operationId: streamerLive
      summary: Get live streamers
      description: |
        Get basic info about currently streaming users.

        This API is very fast and cheap on lichess side.
        So you can call it quite often (like once every 5 seconds).
      tags:
        - Users
      security:
        - None: []
          SameOrigin: []
  /api/crosstable/{user1}/{user2}:
    get:
      operationId: apiCrosstable
      summary: Get crosstable
      description: |
        Get total number of games, and current score, of any two users.

        If the `matchup` flag is provided, and the users are currently playing, also gets the current match game number and scores.
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/following:
    get:
      operationId: apiUserFollowing
      summary: Get users followed by a user
      description: |
        **Users are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Relations
      security:
        - None: []
  /api/user/{username}/followers:
    get:
      operationId: apiUserFollowers
      summary: Get users who follow a user
      description: |
        **Users are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Relations
      security:
        - None: []
  /api/stream/event:
    get:
      operationId: apiStreamEvent
      summary: Stream incoming events
      description: "\n
      \ Stream the events reaching a lichess user in real time as [ndjson](http://ndjson.org/).\n\n
      \ Each line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameStart` Start of a game\n
      \ - `gameFinish` Completion of a game\n
      \ - `challenge` A player sends you a challenge\n
      \ - `challengeCanceled` A player cancels their challenge to you\n
      \ - `challengeDeclined` The opponent declines your challenge\n
      \n
      \ When the stream opens, all current challenges and games are sent."
      tags:
        - Board
        - Bot
        - Challenges
      security:
        - OAuth2: ["challenge:read", "bot:play", "board:play"]
  /api/board/seek:
    post:
      operationId: apiBoardSeek
      summary: Create a seek
      description: "\n
      \ Create a public seek, to start a game with a random player.\n\n
      \ The response is streamed but doesn't contain any information. **Keep the connection open to keep the seek active**.\n\n
      \ If the client closes the connection, the seek is canceled.\n\n
      \ If the seek is accepted, or expires, the server closes the connection.\n\n
      \ **Make sure to also have an [Event stream](#operation/apiStreamEvent) open**, to be notified when a game starts.\n
      \ We recommend opening the [Event stream](#operation/apiStreamEvent) first, then the seek stream. This way,\n
      \ you won't miss the game event if the seek is accepted immediately."
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/stream/{gameId}:
    get:
      operationId: boardGameStream
      summary: Stream Board game state
      description: "\
      \ Stream the state of a game being played with the Board API, as [ndjson](http://ndjson.org/).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included. Sent when a move is played, a draw is offered, or when the game ends.\n
      \ - `chatLine` Chat message sent by a user in the `room` \"player\" or \"spectator\".\n\n
      \nThe first line is always of type `gameFull`."
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/move/{move}:
    post:
      operationId: boardGameMove
      summary: Make a Board move
      description: |
        Make a move in a game being played with the Board API.

        The move can also contain a draw offer/agreement.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/chat:
    post:
      operationId: boardGameChat
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/abort:
    post:
      operationId: boardGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/resign:
    post:
      operationId: boardGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/draw/{accept}:
    post:
      operationId: boardGameDraw
      summary: Handle draw offers
      description: |
        Create/accept/decline draw offers.
        - `yes`: Offer a draw, or accept the opponent's draw offer.
        - `no`: Decline a draw offer from the opponent.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/bot/account/upgrade:
    post:
      operationId: botAccountUpgrade
      summary: Upgrade to Bot account
      description: |
        Upgrade a lichess player account into a Bot account. Only Bot accounts can use the Bot API.

        The account **cannot have played any game** before becoming a Bot account. The upgrade is **irreversible**. The account will only be able to play as a Bot.

        To upgrade an account to Bot, use the [official lichess-bot client](https://github.com/careless25/lichess-bot), or follow these steps:
        - Create an [API access token](https://lichess.org/account/oauth/token/create?scopes[]=bot:play) with "Play bot moves" permission.
        - `curl -d '' https://lichess.org/api/bot/account/upgrade -H "Authorization: Bearer <yourTokenHere>"`

        To know if an account has already been upgraded, use the [Get my profile API](#operation/accountMe):
        the `title` field should be set to `BOT`.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/stream/{gameId}:
    get:
      operationId: botGameStream
      summary: Stream Bot game state
      description: "\
      \ Stream the state of a game being played with the Bot API, as [ndjson](http://ndjson.org/).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included.\n
      \ - `chatLine` Chat message sent by a user (or the bot itself) in the `room` \"player\" or \"spectator\".\n\n
      \nThe first line is always of type `gameFull`."
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/move/{move}:
    post:
      operationId: botGameMove
      summary: Make a Bot move
      description: |
        Make a move in a game being played with the Bot API.

        The move can also contain a draw offer/agreement.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/chat:
    post:
      operationId: botGameChat
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/abort:
    post:
      operationId: botGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/resign:
    post:
      operationId: botGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/challenge/{username}:
    post:
      operationId: challengeCreate
      summary: Create a challenge
      description: |
        Challenge someone to play. The targeted player can choose to accept or decline.

        If the challenge is accepted, you will be notified on the [event stream](#operation/apiStreamEvent)
        that a new game has started. The game ID will be the same as the challenge ID.

        If you also have an OAuth token with `challenge:write` scope for the receiving user,
        you can make them accept the challenge immediately by setting the `acceptByToken` field.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/accept:
    post:
      operationId: challengeAccept
      summary: Accept a challenge
      description: |
        Accept an incoming challenge.

        You should receive a `gameStart` event on the [incoming events stream](#operation/apiStreamEvent).
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/decline:
    post:
      operationId: challengeDecline
      summary: Decline a challenge
      description: |
        Decline an incoming challenge.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/cancel:
    post:
      operationId: challengeCancel
      summary: Cancel a challenge
      description: |
        Cancel a challenge you sent, or aborts the game if the challenge was accepted, but the game was not yet played.
        Note that the ID of a game is the same as the ID of the challenge that created it.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/ai:
    post:
      operationId: challengeAi
      summary: Challenge the AI
      description: |
        Start a game with Lichess AI.

        You will be notified on the [event stream](#operation/apiStreamEvent) that a new game has started.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/open:
    post:
      operationId: challengeOpen
      summary: Open-ended challenge
      description: |
        Create a challenge that any 2 players can join.

        Share the URL of the challenge. the first 2 players to click it will be paired for a game.

        The response body also contains `whiteUrl` and `blackUrl`.
        You can control which color each player gets by giving them these URLs,
        instead of the main challenge URL.

        Open challenges expire after 24h.

        To directly pair 2 known players, use [this endpoint](#operation/challengeCreate) instead,
        with the `acceptByToken` parameter.
      tags:
        - Challenges
      security:
        - None: []
  /api/challenge/{gameId}/start-clocks:
    post:
      operationId: challengeStartClocks
      summary: Start clocks of a game
      description: |
        Start the clocks of a game immediately, even if a player has not yet made a move.

        Requires the OAuth tokens of both players with `challenge:write` scope.

        If the clocks have already started, the call will have no effect.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write"]
  /api/bulk-pairing:
    get:
      operationId: bulkPairingGet
      summary: View upcoming bulk pairings
      description: |
        Get a list of upcoming bulk pairings you created.

        Only bulk pairings that are scheduled in the future, or that have a clock start scheduled in the future, are listed.

        Bulk pairings are deleted from the server after the pairings are done and the clocks have started.
      tags:
        - Bulk pairings
      security:
        - OAuth2: ["challenge:bulk"]
    post:
      operationId: bulkPairingCreate
      summary: Create a bulk pairing
      description: |
        Schedule many games at once, up to 24h in advance.

        OAuth tokens are required for all paired players, with the `challenge:write` scope.

        You can schedule up to 500 games every 10 minutes. [Contact us](mailto:contact@lichess.org) if you need higher limits.

        The entire bulk is rejected if:
          - a token is missing
          - a token is present more than once
          - a token lacks the `challenge:write` scope
          - a player account is closed
          - a player is paired more than once
          - a bulk is already scheduled to start at the same time with the same player
          - you have 10 scheduled bulks
          - you have 1000 scheduled games

        Partial bulks are never created. Either it all fails, or it all succeeds.
        When it fails, it does so with an error message explaining the issue.
        Failed bulks are not counted in the rate limiting, they are free.
        Fix the issues, manually or programmatically, then retry to schedule the bulk.

        A successful bulk creation returns a JSON bulk document. Its ID can be used for further operations.
      tags:
        - Bulk pairings
      security:
        - OAuth2: ["challenge:bulk"]
  /api/bulk-pairing/{id}/start-clocks:
    post:
      operationId: bulkPairingStartClocks
      summary: Manually start clocks
      description: |
        Immediately start all clocks of the games of a bulk pairing.

        This overrides the `startClocksAt` value of an existing bulk pairing.

        If the games have not yet been created (`bulk.pairAt` is in the future), then this does nothing.

        If the clocks have already started (`bulk.startClocksAt` is in the past), then this does nothing.
      tags:
        - Bulk pairings
      security:
        - OAuth2: ["challenge:bulk"]
  /api/bulk-pairing/{id}:
    delete:
      operationId: bulkPairingDelete
      summary: Cancel a bulk pairing
      description: |
        Cancel and delete a bulk pairing that is scheduled in the future.

        If the games have already been created, then this does nothing.

        Canceling a bulk pairing does not refund the rate limit cost of that bulk pairing.
      tags:
        - Bulk pairings
      security:
        - OAuth2: ["challenge:bulk"]
  /api/round/{gameId}/add-time/{seconds}:
    post:
      operationId: roundAddTime
      summary: Add time to the opponent clock
      description: |
        Add seconds to the opponent's clock. Can be used to create games with time odds.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write"]
  /api/challenge/admin/{orig}/{dest}:
    post:
      operationId: challengeCreateAdmin
      summary: Create an admin challenge
      description: |
        **For administrators only. You are not allowed to use this endpoint. Use [Create a challenge](#operation/challengeCreate) instead.**

        Create a challenge between any two players, without OAuth tokens.
        The challenge will be immediately accepted, and a game created.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write"]
  /inbox/{username}:
    post:
      operationId: inboxUsername
      summary: Send a private message
      description: |
        Send a private message to another player.
      tags:
        - Messaging
      security:
        - OAuth2: ["msg:write"]
          SameOrigin: []
  /api/cloud-eval:
    get:
      operationId: apiCloudEval
      summary: Get cloud evaluation of a position.
      description: |
        Get the cached evaluation of a position, if available.

        Opening positions have more chances of being available. There are about 7 million positions in the database.

        Up to 5 variations may be available. Variants are supported.
      tags:
        - Analysis
      security:
        - None: []
  /master:
    get:
      operationId: openingExplorerMaster
      summary: Master games
      description: |
        **Endpoint: https://explorer.lichess.ovh/master**

        Example: `curl https://explorer.lichess.ovh/master?fen=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201`
      tags:
        - Opening Explorer
      security:
        - None: []
  /lichess:
    get:
      operationId: openingExplorerLichess
      summary: Lichess games
      description: |
        **Endpoint: https://explorer.lichess.ovh/lichess**

        Runs https://github.com/niklasf/lila-openingexplorer.

        Example: `curl https://explorer.lichess.ovh/lichess?variant=standard&speeds[]=blitz&speeds[]=rapid&speeds[]=classical&ratings[]=2200&ratings[]=2500&fen=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201`
      tags:
        - Opening Explorer
      security:
        - None: []
  /master/pgn/{gameId}:
    get:
      operationId: openingExplorerMasterGame
      summary: OTB master game
      description: |
        **Endpoint: https://explorer.lichess.ovh/master/pgn/{gameId}**

        Example: `curl https://explorer.lichess.ovh/master/pgn/aAbqI4ey`
      tags:
        - Opening Explorer
      security:
        - None: []
  /stats:
    get:
      operationId: openingExplorerStats
      summary: Opening explorer stats
      description: |
        **Endpoint: https://explorer.lichess.ovh/stats**

        Example: `curl https://explorer.lichess.ovh/stats`
      tags:
        - Opening Explorer
      security:
        - None: []
  /standard:
    get:
      operationId: tablebaseStandard
      summary: Tablebase lookup
      description: |
        **Endpoint: https://tablebase.lichess.ovh**

        Runs https://github.com/niklasf/lila-tablebase with `--sloppy-real-wdl`.

        Example: `curl http://tablebase.lichess.ovh/standard?fen=4k3/6KP/8/8/8/8/7p/8_w_-_-_0_1`
      tags:
        - Tablebase
      security:
        - None: []
  /atomic:
    get:
      operationId: tablebaseAtomic
      summary: Tablebase lookup for Atomic chess
      tags:
        - Tablebase

  /antichess:
    get:
      operationId: antichessAtomic
      summary: Tablebase lookup for Antichess
      tags:
        - Tablebase


components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: "### Authorization Code Flow\n\
        \ The authorization code flow allows your users to **login with lichess**.\n\
        \ - [NodeJS example](https://github.com/lichess-org/api/tree/master/example/oauth-authorization-code)\n\
        \ - [Flask/Python example](https://github.com/lakinwecker/lichess-oauth-flask)\n\
        \ - [NodeJS Passport strategy to login with Lichess OAuth2](https://www.npmjs.com/package/passport-lichess)\n\
        \ - [Create a Lichess OAuth app](https://lichess.org/account/oauth/app)\n\
        \ - [About authorization code flow](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2#grant-type-authorization-code)\n\
        \n#### Real life Oauth2 Authorization Code Flow examples\n\
        \ - [PyChess](https://github.com/gbtami/pychess-variants) ([source code](https://github.com/gbtami/pychess-variants))\n\
        \ - [Lichess4545](https://www.lichess4545.com/) ([source code](https://github.com/cyanfish/heltour))\n\
        \ - [English Chess Federation](https://ecf.octoknight.com/)\n\
        \ - [Rotherham Online Chess](https://rotherhamonlinechess.azurewebsites.net/tournaments)\n\
        \n### Personal API Token\n\
        \ Personal API tokens allow you to quickly interact with Lichess OAuth API.\n\
        \ - `curl https://lichess.org/api/account -H \"Authorization: Bearer <token>\"`\n\
        \ - [NodeJS example](https://github.com/lichess-org/api/tree/master/example/oauth-personal-token)\n\
        \ - [Generate a personal API token](https://lichess.org/account/oauth/token)"
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.lichess.org/oauth/authorize
          tokenUrl: https://oauth.lichess.org/oauth
          scopes:
            "preference:read": Read your preferences
            "preference:write": Write your preferences
            "email:read": Read your email address
            "challenge:read": Read incoming challenges
            "challenge:write": Create, accept, decline challenges
            "challenge:bulk": Create, delete, query bulk pairings
            "study:read": Read private studies and broadcasts
            "study:write": Create, update, delete studies and broadcasts
            "tournament:write": Create tournaments
            "puzzle:read": Read puzzle activity
            "team:write": Join, leave, and manage teams
            "msg:write": Send private messages to other players
            "board:play": Play with the Board API
            "bot:play": Play with the Bot API. Only for [Bot accounts](#operation/botAccountUpgrade)
    SameOrigin:
      description: "CORS is supported on almost all endpoints, except those tagged `SameOrigin`.\n\
        \ If you need CORS on one of those, please\n\
        \ [make an issue](https://github.com/ornicar/lila/issues/new)\n\
        \ explaining your use case to request it."
      type: none
    None:
      description: "No authorization required.\n\
        \ For requests that don't need an authenticated user."
      type: none
