openapi: "3.1.0"
info:
  version: 2.0.0
  title: Lichess.org API reference
  contact:
    name: "Lichess.org API"
    url: "https://lichess.org/api"
    email: "contact@lichess.org"
  x-logo:
    url: https://lichess1.org/assets/logo/lichess-pad12.svg
  license:
    name: AGPL-3.0-or-later
    url: https://www.gnu.org/licenses/agpl-3.0.txt
  description: |
    # Introduction
    Welcome to the reference for the Lichess API! Lichess is free/libre,
    open-source chess server powered by volunteers and donations.
    - Get help in the [Lichess Discord channel](https://discord.gg/lichess)
    - API demo app with OAuth2 login and gameplay: [source](https://github.com/lichess-org/api-demo) / [demo](https://lichess-org.github.io/api-demo/)
    - API UI app with OAuth2 login and endpoint forms: [source](https://github.com/lichess-org/api-ui) / [website](https://lichess.org/api/ui)
    - [Contribute to this documentation on Github](https://github.com/lichess-org/api)
    - Check out [Lichess widgets to embed in your website](https://lichess.org/developers)
    - [Download all Lichess rated games](https://database.lichess.org/)
    - [Download all Lichess puzzles with themes, ratings and votes](https://database.lichess.org/#puzzles)
    - [Download all evaluated positions](https://database.lichess.org/#evals)

    ## Endpoint
    All requests go to `https://lichess.org` (unless otherwise specified).

    ## Clients
    - [Python general API](https://github.com/lichess-org/berserk)
    - [MicroPython general API](https://github.com/mkomon/uberserk)
    - [Python general API - async](https://pypi.org/project/async-lichess-sdk)
    - [Python Lichess Bot](https://github.com/lichess-bot-devs/lichess-bot)
    - [Python Board API for Certabo](https://github.com/haklein/certabo-lichess)
    - [Java general API](https://github.com/tors42/chariot)
    - [JavaScript & TypeScript general API](https://github.com/devjiwonchoi/equine)

    ## Rate limiting
    All requests are rate limited using various strategies,
    to ensure the API remains responsive for everyone.
    Only make one request at a time.
    If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429),
    please wait a full minute before resuming API usage.

    ## Streaming with ND-JSON
    Some API endpoints stream their responses as [Newline Delimited JSON a.k.a. **nd-json**](https://github.com/ndjson/ndjson-spec), with one JSON object per line.

    Here's a [JavaScript utility function](https://gist.github.com/ornicar/a097406810939cf7be1df8ea30e94f3e) to help reading NDJSON streamed responses.

    ## Authentication
    ### Which authentication method is right for me?
    [Read about the Lichess API authentication methods and code examples](https://github.com/lichess-org/api/blob/master/example/README.md)

    ### Personal Access Token
    Personal API access tokens allow you to quickly interact with Lichess API without going through an OAuth flow.
    - [Generate a personal access token](https://lichess.org/account/oauth/token)
    - `curl https://lichess.org/api/account -H "Authorization: Bearer {token}"`
    - [NodeJS example](https://github.com/lichess-org/api/tree/master/example/oauth-personal-token)

    ### Authorization Code Flow with PKCE
    The authorization code flow with PKCE allows your users to **login with Lichess**.
    Lichess supports unregistered and public clients (no client authentication, choose any unique client id).
    The only accepted code challenge method is `S256`.
    Access tokens are long-lived (expect one year), unless they are revoked.
    Refresh tokens are not supported.

    See the [documentation for the OAuth endpoints](#tag/OAuth) or
    the [PKCE RFC](https://datatracker.ietf.org/doc/html/rfc7636#section-4) for a precise protocol description.

    - [Demo app](https://lichess-org.github.io/api-demo/)
    - [Minimal client-side example](https://github.com/lichess-org/api/tree/master/example/oauth-app)
    - [Flask/Python example](https://github.com/lakinwecker/lichess-oauth-flask)
    - [Java example](https://github.com/tors42/lichess-oauth-pkce-app)
    - [NodeJS Passport strategy to login with Lichess OAuth2](https://www.npmjs.com/package/passport-lichess)

    #### Real life examples
    - [PyChess](https://github.com/gbtami/pychess-variants) ([source code](https://github.com/gbtami/pychess-variants))
    - [Lichess4545](https://www.lichess4545.com/) ([source code](https://github.com/cyanfish/heltour))
    - [English Chess Federation](https://ecf.octoknight.com/)
    - [Rotherham Online Chess](https://rotherhamonlinechess.azurewebsites.net/tournaments)

    ### Token format
    Access tokens and authorization codes match `^[A-Za-z0-9_]+$`.
    The length of tokens can be increased without notice. Make sure your application can handle at least 512 characters.
    By convention tokens have a recognizable prefix, but do not rely on this.
servers:
  - url: https://lichess.org
tags:
- name: Account
  description: |
    Read and write account information and preferences.
    <https://lichess.org/account/preferences/game-display>
- name: Users
  description: |
    Access registered users on Lichess.
    <https://lichess.org/player>

    - Each user blog exposes an atom (RSS) feed, like <https://lichess.org/@/thibault/blog.atom>
    - User blogs mashup feed: https://lichess.org/blog/community.atom
    - User blogs mashup feed for a language: https://lichess.org/blog/community/fr.atom

- name: Relations
  description: |
    Access relations between users.
- name: Games
  description: |
    Access games played on Lichess.
    <https://lichess.org/games>
- name: TV
  description: |
    Access Lichess TV channels and games.
    <https://lichess.org/tv> & <https://lichess.org/games>
- name: Puzzles
  description: |
    Access Lichess [puzzle history and dashboard](https://lichess.org/training).

    Our collection of puzzles is in the public domain, you can [download it here](https://database.lichess.org/#puzzles).
    For a list of our puzzle themes with their description, check out the [theme translation file](https://github.com/ornicar/lila/blob/master/translation/source/puzzleTheme.xml).
    The daily puzzle can be [posted in your slack workspace](https://lichess.org/daily-puzzle-slack).
- name: Teams
  description: |
    Access and manage Lichess teams and their members.
    <https://lichess.org/team>
- name: Board
  description: "Play on Lichess with physical boards and third-party clients.\n
  \ Works with normal Lichess accounts. Engine play or assistance is [forbidden](https://lichess.org/page/fair-play).\n\n\
  \n### Features\n\
  \ - [Stream incoming chess moves](#operation/boardGameStream)\n\
  \ - [Play chess moves](#operation/boardGameMove)\n\
  \ - [Read](#operation/boardGameStream) and [write](#operation/boardGameChatPost) in the player and spectator chats\n\
  \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges\n\
  \ - [Abort](#operation/boardGameAbort) and [resign](#operation/boardGameResign) games\n\
  \ - Compatible with normal Lichess accounts\n\n
  \n### Restrictions\n\
  \ - Engine assistance, or any kind of outside help, is [forbidden](https://lichess.org/page/fair-play)\n\
  \ - Time controls: [Rapid, Classical and Correspondence](https://lichess.org/faq#time-controls) only.\n\
  \   For direct challenges and games vs AI, Blitz is also possible.\n\
  \n### Links\n\
  \ - [Announcement](https://lichess.org/blog/XlRW5REAAB8AUJJ-/welcome-lichess-boards)\n\
  \ - [Implementation example](https://github.com/lichess-org/api-demo) and [live demo](https://lichess-org.github.io/api-demo/)\n\n
  \ - [Certabo support](https://github.com/haklein/certabo-lichess)\n\
  \ - [Lichs (play from command-line)](https://github.com/Cqsi/lichs)\n\
  \ - [Lichess discord bot](https://top.gg/bot/707287095911120968)\n\
  \ - [cli-chess](https://github.com/trevorbayless/cli-chess/)"
- name: Bot
  description: "Play on Lichess as a bot. Allows engine play.\n
  \ Read the [blog post announcement of lichess bots](https://lichess.org/blog/WvDNticAAMu_mHKP/welcome-lichess-bots).\n\n
  \ Only works with [Bot accounts](#operation/botAccountUpgrade).\n\n\
  \n### Features\n\
  \ - [Stream incoming chess moves](#operation/botGameStream)\n\
  \ - [Play chess moves](#operation/botGameMove)\n\
  \ - [Read](#operation/botGameStream) and [write](#operation/botGameChat) in the player and spectator chats\n\
  \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges\n\
  \ - [Abort](#operation/botGameAbort) and [resign](#operation/botGameResign) games\n\
  \ - Engine assistance is [allowed](https://lichess.org/page/fair-play)\n\
  \n### Restrictions\n\
  \ - Bots can only play challenge games:  pools and tournaments are off-limits\n\
  \ - Bots cannot play UltraBullet (¼+0) because it requires making too many requests. But 0+1 and ½+0 are allowed.\n\
  \ - Bots must follow [Lichess TOS](https://lichess.org/terms-of-service) specifically Sandbagging, Constant Aborting, Boosting, etc\n\
  \ - Bot devs are advised to make their Bots play casual only when testing their Bots logic and to avoid breaking Lichess TOS.\n\
  \n### Integrations\n\
  \ - [Python3 lichess-bot](https://github.com/lichess-bot-devs/lichess-bot) (official)\n\
  \ - [Python3 lichess UCI bot](https://github.com/Torom/BotLi)\n\
  \ - [JavaScript bot-o-tron](https://github.com/tailuge/bot-o-tron)\n\
  \ - [Golang lichess-bot](https://github.com/dolegi/lichess-bot)\n\
  \ - [Electronic Chessboard](http://www.oliviermercier.com/res/projects/chessboard/)
  \ - Yours? Please make [an issue or pull request](https://github.com/lichess-org/api).\n\
  \n### Links\n\
  \ - [Announcement](https://lichess.org/blog/WvDNticAAMu_mHKP/welcome-lichess-bots)\n\
  \ - Join the [Lichess Bots team](https://lichess.org/team/lichess-bots) with your bot account\n\
  \ - [Get help in the discord channel](https://discord.gg/quwueFd)\n\
  \ - Watch [Lichess Bot TV](https://lichess.org/tv/bot)"
- name: Challenges
  description: |
    Send and receive challenges to play.

    To create a lot of challenges, consider [bulk pairing](#operation/bulkPairingCreate) instead.
- name: Bulk pairings
  description: |
    Create many games for other players.

    These endpoints are intended for tournament organisers.
- name: Arena tournaments
  description: |
    Access Arena tournaments played on Lichess.
    [Official Arena tournaments](https://lichess.org/tournament) are maintained by Lichess,
    but you can [create your own Arena tournaments](https://lichess.org/tournament/new) as well.
- name: Swiss tournaments
  description: |
    Access Swiss tournaments played on Lichess.
    [Read more about Swiss tournaments.](https://lichess.org/swiss).
- name: Simuls
  description: |
    Access simuls played on Lichess.
    <https://lichess.org/simul>
- name: Studies
  description: |
    Access Lichess studies.
    <https://lichess.org/study>
- name: Messaging
  description: |
    Private messages with other players.
    <https://lichess.org/inbox>
- name: Broadcasts
  description: |
    Relay chess events on Lichess.
    [Official broadcasts](https://lichess.org/broadcast) are maintained by Lichess,
    but you can [create your own broadcasts](https://lichess.org/broadcast/new) to cover any live game or chess event.
    You will need to publish PGN on a public URL so that Lichess can pull updates from it.
    Alternatively, you can push PGN updates to Lichess using [this API endpoint](#tag/Broadcasts/operation/broadcastPush).

    Broadcasts are organized in tournaments, which have several rounds, which have several games.
    You must first create a tournament, then you can add rounds to them.
- name: Analysis
  description: |
    Access Lichess cloud evaluations database.
    <https://lichess.org/analysis>
- name: External engine
  description: |
    **This API is in alpha and subject to change.**

    Use or provide external engine analysis.

    External engines can provide analysis on pages like the
    [analysis board](https://lichess.org/analysis), running as a service
    outside of the browser, or even on a different machine.
- name: Opening Explorer
  description: |
    Lookup positions from the [Lichess opening explorer](https://lichess.org/analysis#explorer).

    Runs <https://github.com/niklasf/lila-openingexplorer>.

    **The endpoint hostname is not lichess.org but explorer.lichess.ovh.**
- name: Tablebase
  description: |
    Lookup positions from the [Lichess tablebase server](https://lichess.org/blog/W3WeMyQAACQAdfAL/7-piece-syzygy-tablebases-are-complete).

    **The endpoint hostname is not lichess.org but tablebase.lichess.ovh.**
- name: OAuth
  description: |
    Obtaining and revoking OAuth tokens.

    [Read about the Lichess API authentication methods and code examples](https://github.com/lichess-org/api/blob/master/example/README.md).
paths:
  /api/users/status:
    get:
      operationId: apiUsersStatus
      summary: Get real-time users status
      description: |
        Read the `online`, `playing` and `streaming` flags of several users.

        This API is very fast and cheap on lichess side.
        So you can call it quite often (like once every 5 seconds).

        Use it to track players and know when they're connected on lichess and playing games.
      tags:
        - Users
      security: []
  /api/player:
    get:
      operationId: player
      summary: Get all top 10
      tags:
        - Users
      security: []
      description: |
        Get the top 10 players for each speed and variant.

        See <https://lichess.org/player>.
  /api/player/top/{nb}/{perfType}:
    get:
      operationId: playerTopNbPerfType
      summary: Get one leaderboard
      tags:
        - Users
      security: []
      description: |
        Get the leaderboard for a single speed or variant (a.k.a. `perfType`).
        There is no leaderboard for correspondence or puzzles.

        See <https://lichess.org/player/top/200/bullet>.
  /api/user/{username}:
    get:
      operationId: apiUser
      summary: Get user public data
      description: |
        Read public data of a user.

        If the request is [authenticated with OAuth2](#section/Introduction/Authentication),
        then extra fields might be present in the response: `followable`, `following`, `blocking`, `followsYou`.
      tags:
        - Users
      security:
        - OAuth2: []
  /api/user/{username}/rating-history:
    get:
      operationId: apiUserRatingHistory
      summary: Get rating history of a user
      description: |
        Read rating history of a user, for all perf types.
        There is at most one entry per day.
        Format of an entry is `[year, month, day, rating]`.
        `month` starts at zero (January).
      tags:
        - Users
      security: []
  /api/user/{username}/perf/{perf}:
    get:
      operationId: apiUserPerf
      summary: Get performance statistics of a user
      description: |
        Read performance statistics of a user, for a single performance.
        Similar to the [performance pages on the website](https://lichess.org/@/thibault/perf/bullet).
      tags:
        - Users
      security: []
  /api/user/{username}/activity:
    get:
      operationId: apiUserActivity
      summary: Get user activity
      description: |
        Read data to generate the activity feed of a user.
      tags:
        - Users
      security: []
  /api/puzzle/daily:
    get:
      operationId: apiPuzzleDaily
      summary: Get the daily puzzle
      description: |
        Get the daily Lichess puzzle in JSON format.

        Alternatively, you can [post it in your slack workspace](https://lichess.org/daily-puzzle-slack).
      tags:
        - Puzzles
      security: []
  /api/puzzle/{id}:
    get:
      operationId: apiPuzzleId
      summary: Get a puzzle by its ID
      description: Get a single Lichess puzzle in JSON format.
      tags:
        - Puzzles
      security: []
  /api/puzzle/activity:
    get:
      operationId: apiPuzzleActivity
      summary: Get your puzzle activity
      description: |
        Download your puzzle activity in [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Puzzle activity is sorted by reverse chronological order (most recent first)

        We recommend streaming the response, for it can be very long.
      tags:
        - Puzzles
      security:
        - OAuth2: ["puzzle:read"]
  /api/puzzle/dashboard/{days}:
    get:
      operationId: apiPuzzleDashboard
      summary: Get your puzzle dashboard
      description: |
        Download your [puzzle dashboard](https://lichess.org/training/dashboard/30/dashboard) as JSON.

        Also includes all puzzle themes played, with aggregated results.

        Allows re-creating the [improvement/strengths](https://lichess.org/training/dashboard/30/improvementAreas) interfaces.
      tags:
        - Puzzles
      security:
        - OAuth2: ["puzzle:read"]
  /api/storm/dashboard/{username}:
    get:
      operationId: apiStormDashboard
      summary: Get the storm dashboard of a player
      description: |
        Download the [storm dashboard](https://lichess.org/storm/dashboard/mrbasso) of any player as JSON.

        Contains the aggregated highscores, and the history of storm runs aggregated by days.

        Use `?days=0` if you only care about the highscores.
      tags:
        - Puzzles
      security: []
  /api/racer:
    post:
      operationId: racerPost
      summary: Create and join a puzzle race
      description: |
        Create a new private [puzzle race](https://lichess.org/racer).
        The Lichess user who creates the race must join the race page,
        and manually start the race when enough players have joined.

        - <https://lichess.org/racer>
      tags:
        - Puzzles
      security:
        - OAuth2: ["racer:write"]
  /api/users:
    post:
      operationId: apiUsers
      summary: Get users by ID
      tags:
        - Users
      security: []
      description: |
        Get up to 300 users by their IDs. Users are returned in the same order as the IDs.

        The method is `POST` to allow a longer list of IDs to be sent in the request body.

        Please do not try to download all the Lichess users with this endpoint, or any other endpoint.
        An API is not a way to fully export a website. We do not provide a full download of the Lichess users.

        This endpoint is limited to 8,000 users every 10 minutes, and 120,000 every day.
  /api/account:
    get:
      operationId: accountMe
      summary: Get my profile
      description: |
        Public information about the logged in user.
      tags:
        - Account
      security:
        - OAuth2: []
  /api/account/email:
    get:
      operationId: accountEmail
      summary: Get my email address
      description: |
        Read the email address of the logged in user.
      tags:
        - Account
      security:
        - OAuth2: ["email:read"]
  /api/account/preferences:
    get:
      operationId: account
      summary: Get my preferences
      description: |
        Read the preferences of the logged in user.

        - <https://lichess.org/account/preferences/game-display>
        - <https://github.com/ornicar/lila/blob/master/modules/pref/src/main/Pref.scala>
      tags:
        - Account
      security:
        - OAuth2: ["preference:read"]
  /api/account/kid:
    get:
      operationId: accountKid
      summary: Get my kid mode status
      description: |
        Read the kid mode status of the logged in user.

        - <https://lichess.org/account/kid>
      tags:
        - Account
      security:
        - OAuth2: ["preference:read"]
    post:
      operationId: accountKidPost
      summary: Set my kid mode status
      description: |
        Set the kid mode status of the logged in user.

        - <https://lichess.org/account/kid>
      tags:
        - Account
      security:
        - OAuth2: ["preference:write"]
  /api/timeline:
    get:
      operationId: timeline
      summary: Get my timeline
      description: |
        Get the timeline events of the logged in user.
      tags:
        - Account
      security:
        - OAuth2: []
  /game/export/{gameId}:
    get:
      operationId: gamePgn
      summary: Export one game
      description: |
        Download one game in either PGN or JSON format.

        Ongoing games are delayed by a few seconds ranging from 3 to 60 depending on the time control, as to prevent cheat bots from using this API.
      tags:
        - Games
      security: []
  /api/user/{username}/current-game:
    get:
      operationId: apiUserCurrentGame
      summary: Export ongoing game of a user
      description: |
        Download the ongoing game, or the last game played, of a user.
        Available in either PGN or JSON format.

        Ongoing games are delayed by a few seconds ranging from 3 to 60 depending on the time control, as to prevent cheat bots from using this API.
      tags:
        - Games
      security: []
  /api/games/user/{username}:
    get:
      operationId: apiGamesUser
      summary: Export games of a user
      description: |
        Download all games of any user in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Games are sorted by reverse chronological order (most recent first).

        We recommend streaming the response, for it can be very long.
        <https://lichess.org/@/german11> for instance has more than 500,000 games.

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Introduction/Authentication) request: 30 games per second
          - Authenticated, downloading your own games: 60 games per second
      tags:
        - Games
      security:
        - OAuth2: []
  /api/games/export/_ids:
    post:
      operationId: gamesExportIds
      summary: Export games by IDs
      description: |
        Download games by IDs in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request `Accept` header.

        Games are sorted by reverse chronological order (most recent first)

        The method is `POST` so a longer list of IDs can be sent in the request body.

        300 IDs can be submitted.

        Ongoing games are delayed by a few seconds ranging from 3 to 60 depending on the time control, as to prevent cheat bots from using this API.
      tags:
        - Games
      security: []
  /api/stream/games-by-users:
    post:
      operationId: gamesByUsers
      summary: Stream games of users
      description: |
        Stream the games played between a list of users, in real time.
        Only games where **both players** are part of the list are included.

        The stream emits an event each time a game is started or finished.

        To also get all current ongoing games at the beginning of the stream, use the `withCurrentGames` flag.

        Games are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        Maximum number of users: 300.

        The method is `POST` so a longer list of IDs can be sent in the request body.
      tags:
        - Games
      security: []
  /api/stream/games/{streamId}:
    post:
      operationId: gamesByIds
      summary: Stream games by IDs
      description: |
        Creates a stream of games from an arbitrary streamId, and a list of game IDs.

        The stream first outputs the games that already exists, then emits an event each time a game is started or finished.

        Games are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        Maximum number of games: 500 for anonymous requests, or 1000 for [OAuth2 authenticated](#section/Introduction/Authentication) requests.

        While the stream is open, it is possible to [add new game IDs to watch](#operation/gamesByIdsAdd).
      tags:
        - Games
      security: []
  /api/stream/games/{streamId}/add:
    post:
      operationId: gamesByIdsAdd
      summary: Add game IDs to stream
      description: |
        Add new game IDs for [an existing stream](#operation/gamesByIds) to watch.
        The stream will immediately outputs the games that already exists, then emit an event each time a game is started or finished.
      tags:
        - Games
      security: []
  /api/account/playing:
    get:
      operationId: apiAccountPlaying
      summary: Get my ongoing games
      description: |
        Get the ongoing games of the current user.
        Real-time and correspondence games are included.
        The most urgent games are listed first.
      tags:
        - Games
      security:
        - OAuth2: []
  /api/stream/game/{id}:
    get:
      operationId: streamGame
      summary: Stream moves of a game
      description: |
        Stream positions and moves of any ongoing game, in [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        A description of the game is sent as a first message.
        Then a message is sent each time a move is played.
        Finally a description of the game is sent when it finishes, and the stream is closed.

        Ongoing games are delayed by a few seconds ranging from 3 to 60 depending on the time control, as to prevent cheat bots from using this API.

        No more than 8 game streams can be opened at the same time from the same IP address.
      tags:
        - Games
      security: []
  /api/import:
    post:
      operationId: gameImport
      summary: Import one game
      description: |
        Import a game from PGN. See <https://lichess.org/paste>.

        Rate limiting: 200 games per hour for OAuth requests, 100 games per hour for anonymous requests.

        To broadcast ongoing games, consider [pushing to a broadcast instead](#operation/broadcastPush).

        To analyse a position or a line, just construct an analysis board URL:
        [https://lichess.org/analysis/pgn/e4_e5_Nf3_Nc6_Bc4_Bc5_Bxf7+](https://lichess.org/analysis/pgn/e4_e5_Nf3_Nc6_Bc4_Bc5_Bxf7+)
      tags:
        - Games
      security:
        - OAuth2: []
  /api/games/export/imports:
    get:
      operationId: apiImportedGamesUser
      summary: Export your imported games
      description : Download all games imported by you. Games are exported in PGN format.
      tags: 
        - Games
      security: 
        - OAuth2: []
  /api/tv/channels:
    get:
      operationId: tvChannels
      summary: Get current TV games
      description: |
        Get basic info about the best games being played for each speed and variant,
        but also computer games and bot games.

        See [lichess.org/tv](https://lichess.org/tv).
      tags:
        - TV
      security: []
  /api/tv/feed:
    get:
      operationId: tvFeed
      summary: Stream current TV game
      description: |
        Stream positions and moves of the current [TV game](https://lichess.org/tv) in [ndjson](#section/Introduction/Streaming-with-ND-JSON).
        A summary of the game is sent as a first message, and when the featured game changes.

        Try it with `curl https://lichess.org/api/tv/feed`.
      tags:
        - TV
      security: []
  /api/tv/{channel}:
    get:
      operationId: tvChannelGames
      summary: Get best ongoing games of a TV channel
      description: |
        Get a list of ongoing games for a given TV channel. Similar to [lichess.org/games](https://lichess.org/games).

        Available in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request `Accept` header.
      tags:
        - TV
      security: []
  /api/tournament:
    get:
      operationId: apiTournament
      summary: Get current tournaments
      description: |
        Get recently finished, ongoing, and upcoming tournaments.

        This API is used to display the [Lichess tournament schedule](https://lichess.org/tournament).
      tags:
        - "Arena tournaments"
      security: []
    post:
      operationId: apiTournamentPost
      summary: Create a new Arena tournament
      description: |
        Create a public or private Arena tournament.

        This endpoint mirrors the form on <https://lichess.org/tournament/new>.

        You can create up to 12 public tournaments per day, or 24 private tournaments.

        A team battle can be created by specifying the `teamBattleByTeam` argument.

        Additional restrictions:
          - clockTime + clockIncrement > 0
          - 15s and 0+1 variant tournaments cannot be rated
          - Clock time in comparison to tournament length must be reasonable: 3 <= (minutes * 60) / (96 * clockTime + 48 * clockIncrement + 15) <= 150
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}:
    get:
      operationId: tournament
      summary: Get info about an Arena tournament
      description: |
        Get detailed info about recently finished, current, or upcoming tournament's duels, player standings, and other info.
      tags:
        - "Arena tournaments"
      security: []
    post:
      operationId: apiTournamentUpdate
      summary: Update an Arena tournament
      description: |
        Update an Arena tournament.

        Be mindful not to make important changes to ongoing tournaments.

        Can be used to update a team battle.

        Additional restrictions:
          - clockTime + clockIncrement > 0
          - 15s and 0+1 variant tournaments cannot be rated
          - Clock time in comparison to tournament length must be reasonable: 3 <= (minutes * 60) / (96 * clockTime + 48 * clockIncrement + 15) <= 150
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}/join:
    post:
      operationId: apiTournamentJoin
      summary: Join an Arena tournament
      description: |
        Join an Arena tournament, possibly with a password and/or a team.
        Also unpauses if you had previously [paused](#operation/apiTournamentWithdraw) the tournament.
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}/withdraw:
    post:
      operationId: apiTournamentWithdraw
      summary: Pause or leave an Arena tournament
      description: |
        Leave a future Arena tournament, or take a break on an ongoing Arena tournament.
        It's possible to join again later. Points and streaks are preserved.
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}/terminate:
    post:
      operationId: apiTournamentTerminate
      summary: Terminate an Arena tournament
      description: |
        Terminate an Arena tournament
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/team-battle/{id}:
      post:
        operationId: apiTournamentTeamBattlePost
        summary: Update a team battle
        description: |
          Set the teams and number of leaders of a team battle.

          To update the other attributes of a team battle, use the [tournament update endpoint](#operation/apiTournamentUpdate).
        tags:
          - "Arena tournaments"
        security:
          - OAuth2: ["tournament:write"]
  /api/tournament/{id}/games:
    get:
      operationId: gamesByTournament
      summary: Export games of an Arena tournament
      description: |
        Download games of a tournament in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Games are sorted by reverse chronological order (most recent first).

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Introduction/Authentication) request: 30 games per second
      tags:
        - "Arena tournaments"
      security: []
  /api/tournament/{id}/results:
    get:
      operationId: resultsByTournament
      summary: Get results of an Arena tournament
      description: |
        Players of an Arena tournament, with their score and performance, sorted by rank (best first).

        **Players are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON)**, i.e. one JSON object per line.

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      tags:
        - "Arena tournaments"
      security: []
  /api/tournament/{id}/teams:
    get:
      operationId: teamsByTournament
      summary: Get team standing of a team battle
      description: |
        Teams of a team battle tournament, with top players, sorted by rank (best first).
      tags:
        - "Arena tournaments"
      security: []
  /api/user/{username}/tournament/created:
    get:
      operationId: apiUserNameTournamentCreated
      summary: Get tournaments created by a user
      description: |
        Get all tournaments created by a given user.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        Tournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - "Arena tournaments"
      security: []
  /api/swiss/new/{teamId}:
    post:
      operationId: apiSwissNew
      summary: Create a new Swiss tournament
      description: |
        Create a Swiss tournament for your team.

        This endpoint mirrors the Swiss tournament form from your team pagee.

        You can create up to 12 tournaments per day.

        Additional restrictions:
          - clock.limit + clock.increment > 0
          - 15s and 0+1 variant tournaments cannot be rated
      tags:
        - "Swiss tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/swiss/{id}:
    get:
      operationId: swiss
      summary: Get info about a Swiss tournament
      description: |
        Get detailed info about a Swiss tournament.
      tags:
        - "Swiss tournaments"
      security: []
  /api/swiss/{id}/edit:
    post:
      operationId: apiSwissUpdate
      summary: Update a Swiss tournament
      description: |
        Update a Swiss tournament.

        Be mindful not to make important changes to ongoing tournaments.

        Additional restrictions:
          - clock.limit + clock.increment > 0
          - 15s and 0+1 variant tournaments cannot be rated
      tags:
        - "Swiss tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/swiss/{id}/schedule-next-round:
    post:
      operationId: apiSwissScheduleNextRound
      summary: Manually schedule the next round
      description: |
        Manually schedule the next round date and time of a Swiss tournament.

        This sets the `roundInterval` field to `99999999`, i.e. manual scheduling.

        All further rounds will need to be manually scheduled, unless the `roundInterval` field is changed back to automatic scheduling.
      tags:
        - "Swiss tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/swiss/{id}/join:
    post:
      operationId: apiSwissJoin
      summary: Join a Swiss tournament
      description: |
        Join a Swiss tournament, possibly with a password.
      tags:
        - "Swiss tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/swiss/{id}/withdraw:
    post:
      operationId: apiSwissWithdraw
      summary: Pause or leave a swiss tournament
      description: |
        Leave a future Swiss tournament, or take a break on an ongoing Swiss tournament.
        It's possible to join again later. Points are preserved.
      tags:
        - "Swiss tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/swiss/{id}/terminate:
    post:
      operationId: apiSwissTerminate
      summary: Terminate a Swiss tournament
      description: |
        Terminate a Swiss tournament
      tags:
        - "Swiss tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /swiss/{id}.trf:
    get:
      operationId: swissTrf
      summary: Export TRF of a Swiss tournament
      description: |
        Download a tournament in the Tournament Report File format, the FIDE standard.

        Documentation: <https://www.fide.com/FIDE/handbook/C04Annex2_TRF16.pdf>

        Example: <https://lichess.org/swiss/j8rtJ5GL.trf>
      tags:
        - "Swiss tournaments"
      security: []
  /api/swiss/{id}/games:
    get:
      operationId: gamesBySwiss
      summary: Export games of a Swiss tournament
      description: |
        Download games of a swiss tournament in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Games are sorted by reverse chronological order (last round first).

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Introduction/Authentication) request: 30 games per second
      tags:
        - "Swiss tournaments"
      security: []
  /api/swiss/{id}/results:
    get:
      operationId: resultsBySwiss
      summary: Get results of a swiss tournament
      description: |
        Players of a swiss tournament, with their score and performance, sorted by rank (best first).

        Players are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      tags:
        - "Swiss tournaments"
      security: []
  /api/team/{teamId}/swiss:
    get:
      operationId: apiTeamSwiss
      summary: Get team swiss tournaments
      description: |
        Get all swiss tournaments of a team.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        Tournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Teams
        - "Swiss tournaments"
      security: []
  /api/study/{studyId}/{chapterId}.pgn:
    get:
      operationId: studyChapterPgn
      summary: Export one study chapter
      description: |
        Download one study chapter in PGN format.
      tags:
        - Studies
      security: []
  /api/study/{studyId}.pgn:
    get:
      operationId: studyAllChaptersPgn
      summary: Export all chapters
      description: |
        Download all chapters of a study in PGN format.
      tags:
        - Studies
      security: []
    head:
      operationId: studyAllChaptersHead
      summary: Study metadata
      description: |
        Only get the study headers, including `Last-Modified`.
      tags:
        - Studies
      security: []
  /api/study/{studyId}/import-pgn:
    post:
      operationId: apiStudyImportPGN
      summary: Import PGN into a study
      description: |
        Imports arbitrary PGN into an existing [study](https://lichess.org/study). Creates a new chapter in the study.

        If the PGN contains multiple games (separated by 2 or more newlines)
        then multiple chapters will be created within the study.

        Note that a study can contain at most 64 chapters.
      tags:
        - Studies
      security:
        - OAuth2: ["study:write"]
  /study/by/{username}/export.pgn:
    get:
      operationId: studyExportAllPgn
      summary: Export all studies of a user
      description: |
        Download all chapters of all studies of a user in PGN format.

        If authenticated, then all public, unlisted, and private studies are included.

        If not, only public (non-unlisted) studies are included.
      tags:
        - Studies
      security:
        - OAuth2: ["study:read"]
  /api/study/by/{username}:
    get:
      operationId: studyListMetadata
      summary: List studies of a user
      description: |
        Get metadata (name and dates) of all studies of a user.

        If authenticated, then all public, unlisted, and private studies are included.

        If not, only public (non-unlisted) studies are included.

        Studies are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Studies
      security:
        - OAuth2: ["study:read"]
  /api/broadcast:
    get:
      operationId: broadcastIndex
      summary: Get official broadcasts
      description: |
        Get all incoming, ongoing, and finished official broadcasts.
        The broadcasts are sorted by start date, most recent first.

        Broadcasts are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Broadcasts
      security: []
  /broadcast/new:
    post:
      operationId: broadcastTourCreate
      summary: Create a broadcast tournament
      description: |
        Create a new broadcast tournament to relay external games.
        This endpoint accepts the same form data as the [web form](https://lichess.org/broadcast/new).
      tags:
        - Broadcasts
      security:
        - OAuth2: ["study:write"]
  /broadcast/{slug}/{broadcastTournamentId}:
    get:
      operationId: broadcastTourGet
      summary: Get your broadcast tournament
      description: |
        Get information about a broadcast tournament.
      tags:
        - Broadcasts
      security:
        - OAuth2: ["study:read"]
  /broadcast/{broadcastTournamentId}/edit:
      post:
        operationId: broadcastTourUpdate
        summary: Update your broadcast tournament
        description: |
          Update information about a broadcast tournament that you created.
          This endpoint accepts the same form data as the web form.
          All fields must be populated with data. Missing fields will override the broadcast with empty data.
        tags:
          - Broadcasts
        security:
          - OAuth2: ["study:write"]
  /broadcast/{broadcastTournamentId}/new:
    post:
      operationId: broadcastRoundCreate
      summary: Create a broadcast round
      description: |
        Create a new broadcast round to relay external games.
        This endpoint accepts the same form data as the web form.
      tags:
        - Broadcasts
      security:
        - OAuth2: ["study:write"]
  /api/broadcast/{broadcastTournamentSlug}/{broadcastRoundSlug}/{broadcastRoundId}:
    get:
      operationId: broadcastRoundGet
      summary: Get a broadcast round
      description: |
        Get information about a broadcast round.
      tags:
        - Broadcasts
  /broadcast/round/{broadcastRoundId}/edit:
    post:
      operationId: broadcastRoundUpdate
      summary: Update your broadcast round
      description: |
        Update information about a broadcast round that you created.
        This endpoint accepts the same form data as the web form.
        All fields must be populated with data. Missing fields will override the broadcast with empty data.
        For instance, if you omit `startDate`, then any pre-existing start date will be removed.
      tags:
        - Broadcasts
      security:
        - OAuth2: ["study:write"]
  /broadcast/round/{broadcastRoundId}/push:
    post:
      operationId: broadcastPush
      summary: Push PGN to your broadcast round
      description: |
        Update your broadcast with new PGN.
        Only for broadcast without a source URL.
      tags:
        - Broadcasts
      security:
        - OAuth2: ["study:write"]
  /api/stream/broadcast/round/{broadcastRoundId}.pgn:
    get:
      operationId: broadcastStreamRoundPgn
      summary: Stream an ongoing broadcast tournament as PGN
      description: |
        This streaming endpoint first sends all games of a broadcast tournament in PGN format.

        Then, it waits for new moves to be played. As soon as it happens, the entire PGN of the game is sent to the stream.

        The stream will also send PGNs when games are added to the tournament.

        This is the best way to get updates about an ongoing tournament. Streaming means no polling,
        and no pollings means no latency, and minimum impact on the server.
      tags:
        - Broadcasts
      security: []
  /api/broadcast/round/{broadcastRoundId}.pgn:
    get:
      operationId: broadcastRoundPgn
      summary: Export one round as PGN
      description: |
        Download all games of a single round of a broadcast tournament in PGN format.

        You *could* poll this endpoint to get updates about a tournament, but it would be slow,
        and very inneficient.

        Instead, consider [streaming the tournament](#operation/broadcastStreamRoundPgn) to get
        a new PGN every time a game is updated, in real-time.
      tags:
        - Broadcasts
      security: []
  /api/broadcast/{broadcastTournamentId}.pgn:
    get:
      operationId: broadcastAllRoundsPgn
      summary: Export all rounds as PGN
      description: |
        Download all games of all rounds of a broadcast in PGN format.

        If a `study:read` [OAuth token](#tag/OAuth) is provided,
        the private rounds where the user is a contributor will be available.

        You may want to [download only the games of a single round](#operation/broadcastRoundPgn) instead.
      tags:
        - Broadcasts
      security:
        - OAuth2: ["study:read"]
  /api/broadcast/my-rounds:
    get:
      operationId: broadcastMyRoundsGet
      summary: Get your broadcast rounds
      description: |
        Stream all broadcast rounds you are a member of.
        Also includes broadcasts rounds you did not create, but were invited to.
        Also includes broadcasts rounds where you're a non-writing member. See the `writeable` flag in the response.
        Rounds are ordered by rank, which is roughly chronological, most recent first, slightly pondered with popularity.
      tags:
        - Broadcasts
      security:
        - OAuth2: ["study:read"]
  /api/simul:
    get:
      operationId: apiSimul
      summary: Get current simuls
      description: |
        Get recently created, started, finished, simuls.

        Created and finished simul lists are not exhaustives, only those with
        strong enough host will be listed, the same filter is used to display simuls on https://lichess.org/simul.

        When [authenticated with OAuth2](#section/Introduction/Authentication), the pending list will be populated with your created, but unstarted simuls.
      tags:
        - Simuls
      security: []
  /api/team/{teamId}:
    get:
      operationId: teamShow
      summary: Get a single team
      description: Public info about a team. Includes the list of publicly visible leaders.
      tags:
        - Teams
      security: []
  /api/team/all:
    get:
      operationId: teamAll
      summary: Get popular teams
      description: |
        Paginator of the most popular teams.
      tags:
        - Teams
      security: []
  /api/team/of/{username}:
    get:
      operationId: teamOfUsername
      summary: Teams of a player
      description: |
        All the teams a player is a member of.
      tags:
        - Teams
      security: []
  /api/team/search:
    get:
      operationId: teamSearch
      summary: Search teams
      description: |
        Paginator of team search results for a keyword.
      tags:
        - Teams
      security: []
  /api/team/{teamId}/users:
    get:
      operationId: teamIdUsers
      summary: Get members of a team
      description: |
        Members are sorted by reverse chronological order of joining the team (most recent first).
        OAuth is only required if the list of members is private.

        Members are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Teams
      security:
        - OAuth2: ["team:read"]
  /api/team/{teamId}/arena:
    get:
      operationId: apiTeamArena
      summary: Get team Arena tournaments
      description: |
        Get all Arena tournaments relevant to a team.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        Tournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Teams
        - "Arena tournaments"
      security: []
  /team/{teamId}/join:
    post:
      operationId: teamIdJoin
      summary: Join a team
      description: |
        Join a team.
        If the team requires a password but the `password` field is incorrect,
        then the call fails with `403 Forbidden`.
        Similarly, if the team join policy requires a confirmation but the
        `message` parameter is not given, then the call fails with
        `403 Forbidden`.
      tags:
        - Teams
      security:
        - OAuth2: ["team:write"]
  /team/{teamId}/quit:
    post:
      operationId: teamIdQuit
      summary: Leave a team
      description: |
        Leave a team.
        - <https://lichess.org/team>
      tags:
        - Teams
      security:
        - OAuth2: ["team:write"]
  /api/team/{teamId}/requests:
    get:
      operationId: teamRequests
      summary: Get join requests
      description: Get pending join requests of your team
      tags:
        - Teams
      security:
        - OAuth2: ["team:read"]
  ]

  /api/team/{teamId}/request/{userId}/accept:
    post:
      operationId: teamRequestAccept
      summary: Accept join request
      description: Accept someone's request to join your team
      tags:
        - Teams
      security:
        - OAuth2: ["team:lead"]
  /api/team/{teamId}/request/{userId}/decline:
    post:
      operationId: teamRequestDecline
      summary: Decline join request
      description: Decline someone's request to join your team
      tags:
        - Teams
      security:
        - OAuth2: ["team:lead"]
  /api/team/{teamId}/kick/{userId}:
    post:
      operationId: teamIdKickUserId
      summary: Kick a user from your team
      description: |
        Kick a member out of one of your teams.
        - <https://lichess.org/team>
      tags:
        - Teams
      security:
        - OAuth2: ["team:lead"]
  /team/{teamId}/pm-all:
    post:
      operationId: teamIdPmAll
      summary: Message all members
      description: |
        Send a private message to all members of a team.
        You must be a team leader with the "Messages" permission.
      tags:
        - Teams
      security:
        - OAuth2: ["team:lead"]
  /api/streamer/live:
    get:
      operationId: streamerLive
      summary: Get live streamers
      description: |
        Get basic info about currently streaming users.

        This API is very fast and cheap on lichess side.
        So you can call it quite often (like once every 5 seconds).
      tags:
        - Users
      security: []
-Jerry",
                      "twitch": "https://twitch.tv/chessnetwork",
                      "youTube": "https://www.youtube.com/channel/UCCDOQrpqLqKVcTCKzqarxLg/live",
                      "image": "https://image.lichess1.org/display?h=350&op=thumbnail&path=orlandikill:streamer:orlandikill:wiw356Np.jpg&w=350&sig=9912e0c45e42f37e7cd2716af6bd41bb10497b0c"
                    }
                  }
                ]

  /api/crosstable/{user1}/{user2}:
    get:
      operationId: apiCrosstable
      summary: Get crosstable
      description: |
        Get total number of games, and current score, of any two users.

        If the `matchup` flag is provided, and the users are currently playing, also gets the current match game number and scores.
      tags:
        - Users
      security: []
  /api/player/autocomplete:
    get:
      operationId: apiPlayerAutocomplete
      summary: Autocomplete usernames
      description: |
        Provides autocompletion options for an incomplete username.
      tags:
        - Users
      security: []
  /api/user/{username}/note:
    post:
      operationId: writeNote
      summary: Add a note for a user
      description: |
        Add a private note available only to you about this account.
      tags:
        - Users
      security:
        - OAuth2: []
    get:
      operationId: readNote
      summary: Get notes for a user
      description: |
        Get the private notes that you have added for a user.
      tags:
        - Users
      security:
        - OAuth2: []
  /api/rel/following:
    get:
      operationId: apiUserFollowing
      summary: Get users followed by the logged in user
      description: |
        Users are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      tags:
        - Relations
      security:
        - OAuth2: ["follow:read"]
  /api/rel/follow/{username}:
    post:
      operationId: followUser
      summary: Follow a player
      description: |
        Follow a player, adding them to your list of Lichess friends.
      tags:
        - Relations
      security:
        - OAuth2: ["follow:write"]
  /api/rel/unfollow/{username}:
    post:
      operationId: unfollowUser
      summary: Unfollow a player
      description: |
        Unfollow a player, removing them from your list of Lichess friends.
      tags:
        - Relations
      security:
        - OAuth2: ["follow:write"]
  /api/stream/event:
    get:
      operationId: apiStreamEvent
      summary: Stream incoming events
      description: "\n
      \ Stream the events reaching a lichess user in real time as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\n
      \ An empty line is sent every 6 seconds for keep alive purposes.\n\n
      \ Each non-empty line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameStart` Start of a game\n
      \ - `gameFinish` Completion of a game\n
      \ - `challenge` A player sends you a challenge or you challenge someone\n
      \ - `challengeCanceled` A player cancels their challenge to you\n
      \ - `challengeDeclined` The opponent declines your challenge\n
      \n
      \ When the stream opens, all current challenges and games are sent."
      tags:
        - Board
        - Bot
      security:
        - OAuth2: ["challenge:read", "bot:play", "board:play"]
  /api/board/seek:
    post:
      operationId: apiBoardSeek
      summary: Create a seek
      description: "\n
      \ Create a public seek, to start a game with a random player.\n\n
      \ ### Real-time seek\n\n
      \ Specify the `time` and `increment` clock values.
      \ The response is streamed but doesn't contain any information.\n\n
      \ **Keep the connection open to keep the seek active**.\n\n
      \ If the client closes the connection, the seek is canceled. This way, if the client terminates, the user won't be paired in a game they wouldn't play.\n
      \ When the seek is accepted, or expires, the server closes the connection.\n\n
      \ **Make sure to also have an [Event stream](#operation/apiStreamEvent) open**, to be notified when a game starts.\n
      \ We recommend opening the [Event stream](#operation/apiStreamEvent) first, then the seek stream. This way,\n
      \ you won't miss the game event if the seek is accepted immediately.\n\n
      \ ### Correspondence seek\n\n
      \ Specify the `days` per turn value.
      \ The response is not streamed, it immediately completes with the seek ID. The seek remains active on the server until it is joined by someone."
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/stream/{gameId}:
    get:
      operationId: boardGameStream
      summary: Stream Board game state
      description: "\
      \ Stream the state of a game being played with the Board API, as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included. Sent when a move is played, a draw is offered, or when the game ends.\n
      \ - `chatLine` Chat message sent by a user in the `room` \"player\" or \"spectator\".\n\n
      \ - `opponentGone` Whether the opponent has left the game, and how long before you can claim a win or draw.\n\n
      \nThe first line is always of type `gameFull`.\n\n
      \nThe server closes the stream when the game ends, or if the game has already ended."
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/move/{move}:
    post:
      operationId: boardGameMove
      summary: Make a Board move
      description: |
        Make a move in a game being played with the Board API.

        The move can also contain a draw offer/agreement.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/chat:
    post:
      operationId: boardGameChatPost
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
    get:
      operationId: boardGameChatGet
      summary: Fetch the game chat
      description: |
        Get the messages posted in the game chat
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/abort:
    post:
      operationId: boardGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/resign:
    post:
      operationId: boardGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Board API.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/draw/{accept}:
    post:
      operationId: boardGameDraw
      summary: Handle draw offers
      description: |
        Create/accept/decline draw offers.
        - `yes`: Offer a draw, or accept the opponent's draw offer.
        - `no`: Decline a draw offer from the opponent.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/takeback/{accept}:
    post:
      operationId: boardGameTakeback
      summary: Handle takeback offers
      description: |
        Create/accept/decline takebacks.
        - `yes`: Propose a takeback, or accept the opponent's takeback offer.
        - `no`: Decline a takeback offer from the opponent.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/claim-victory:
    post:
      operationId: boardGameClaimVictory
      summary: Claim victory of a game
      description: |
        Claim victory when the opponent has left the game for a while.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/board/game/{gameId}/berserk:
    post:
      operationId: boardGameBerserk
      summary: Berserk a tournament game
      description: |
        Go berserk on an arena tournament game. Halves the clock time, grants an extra point upon winning.
        Only available in arena tournaments that allow berserk, and before each player has made a move.
      tags:
        - Board
      security:
        - OAuth2: ["board:play"]
  /api/bot/online:
    get:
      operationId: apiBotOnline
      summary: Get online bots
      tags:
        - Bot
      security: []
      description: Stream the [online bot users](https://lichess.org/player/bots), as [ndjson](#section/Introduction/Streaming-with-ND-JSON). Throttled to 50 bot users per second.
  /api/bot/account/upgrade:
    post:
      operationId: botAccountUpgrade
      summary: Upgrade to Bot account
      description: |
        Upgrade a lichess player account into a Bot account. Only Bot accounts can use the Bot API.

        The account **cannot have played any game** before becoming a Bot account. The upgrade is **irreversible**. The account will only be able to play as a Bot.

        To upgrade an account to Bot, use the [official lichess-bot client](https://github.com/lichess-bot-devs/lichess-bot), or follow these steps:
        - Create an [API access token](https://lichess.org/account/oauth/token/create?scopes[]=bot:play) with "Play bot moves" permission.
        - `curl -d '' https://lichess.org/api/bot/account/upgrade -H "Authorization: Bearer <yourTokenHere>"`

        To know if an account has already been upgraded, use the [Get my profile API](#operation/accountMe):
        the `title` field should be set to `BOT`.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/stream/{gameId}:
    get:
      operationId: botGameStream
      summary: Stream Bot game state
      description: "\
      \ Stream the state of a game being played with the Bot API, as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included.\n
      \ - `chatLine` Chat message sent by a user (or the bot itself) in the `room` \"player\" or \"spectator\".\n\n
      \ - `opponentGone` Whether the opponent has left the game, and how long before you can claim a win or draw.\n\n
      \nThe first line is always of type `gameFull`."
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/move/{move}:
    post:
      operationId: botGameMove
      summary: Make a Bot move
      description: |
        Make a move in a game being played with the Bot API.

        The move can also contain a draw offer/agreement.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/chat:
    post:
      operationId: botGameChat
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
    get:
      operationId: botGameChatGet
      summary: Fetch the game chat
      description: |
        Get the messages posted in the game chat
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/abort:
    post:
      operationId: botGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/resign:
    post:
      operationId: botGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/draw/{accept}:
    post:
      operationId: botGameDraw
      summary: Handle draw offers in bot games
      description: |
        Create/accept/decline draw offers in bot games
        - `yes`: Offer a draw, or accept the opponent's draw offer.
        - `no`: Decline a draw offer from the opponent.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/challenge:
    get:
      operationId: challengeList
      summary: List your challenges
      description: |
        Get a list of challenges created by or targeted at you.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:read"]
  /api/challenge/{username}:
    post:
      operationId: challengeCreate
      summary: Create a challenge
      description: |
        Challenge someone to play. The targeted player can choose to accept or decline.

        If the challenge is accepted, you will be notified on the [event stream](#operation/apiStreamEvent)
        that a new game has started. The game ID will be the same as the challenge ID.

        Challenges for realtime games (not correspondence) expire after 20s if not accepted.
        To prevent that, use the `keepAliveStream` flag described below.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/accept:
    post:
      operationId: challengeAccept
      summary: Accept a challenge
      description: |
        Accept an incoming challenge.

        You should receive a `gameStart` event on the [incoming events stream](#operation/apiStreamEvent).
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/decline:
    post:
      operationId: challengeDecline
      summary: Decline a challenge
      description: |
        Decline an incoming challenge.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/{challengeId}/cancel:
    post:
      operationId: challengeCancel
      summary: Cancel a challenge
      description: |
        Cancel a challenge you sent, or aborts the game if the challenge was accepted, but the game was not yet played.
        Note that the ID of a game is the same as the ID of the challenge that created it.

        Works for user challenges and open challenges alike.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/ai:
    post:
      operationId: challengeAi
      summary: Challenge the AI
      description: |
        Start a game with Lichess AI.

        You will be notified on the [event stream](#operation/apiStreamEvent) that a new game has started.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play", "board:play"]
  /api/challenge/open:
    post:
      operationId: challengeOpen
      summary: Open-ended challenge
      description: |
        Create a challenge that any 2 players can join.

        Share the URL of the challenge. the first 2 players to click it will be paired for a game.

        The response body also contains `whiteUrl` and `blackUrl`.
        You can control which color each player gets by giving them these URLs,
        instead of the main challenge URL.

        Open challenges expire after 24h.

        If the challenge creation is [authenticated with OAuth2](#section/Introduction/Authentication),
        then you can use the [challenge cancel endpoint](#operation/challengeCancel) to cancel it.

        To directly pair 2 known players, use [this endpoint](#operation/bulkPairingList) instead.
      tags:
        - Challenges
      security: []
  /api/challenge/{gameId}/start-clocks:
    post:
      operationId: challengeStartClocks
      summary: Start clocks of a game
      description: |
        Start the clocks of a game immediately, even if a player has not yet made a move.

        Requires the OAuth tokens of both players with `challenge:write` scope.

        If the clocks have already started, the call will have no effect.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write"]
  /api/bulk-pairing:
    get:
      operationId: bulkPairingList
      summary: View your bulk pairings
      description: |
        Get a list of bulk pairings you created.
      tags:
        - Bulk pairings
      security:
        - OAuth2: ["challenge:bulk"]
    post:
      operationId: bulkPairingCreate
      summary: Create a bulk pairing
      description: |
        Schedule many games at once, up to 24h in advance.

        OAuth tokens are required for all paired players, with the `challenge:write` scope.

        You can schedule up to 500 games every 10 minutes. [Contact us](mailto:contact@lichess.org) if you need higher limits.

        If games have a real-time clock, each player must have only one pairing.
        For correspondence games, players can have multiple pairings within the same bulk.

        The entire bulk is rejected if:
          - a token is missing
          - a token is present more than once (except in correspondence)
          - a token lacks the `challenge:write` scope
          - a player account is closed
          - a player is paired more than once (except in correspondence)
          - a bulk is already scheduled to start at the same time with the same player
          - you have 20 scheduled bulks
          - you have 1000 scheduled games

        Partial bulks are never created. Either it all fails, or it all succeeds.
        When it fails, it does so with an error message explaining the issue.
        Failed bulks are not counted in the rate limiting, they are free.
        Fix the issues, manually or programmatically, then retry to schedule the bulk.

        A successful bulk creation returns a JSON bulk document. Its ID can be used for further operations.
      tags:
        - Bulk pairings
      security:
        - OAuth2: ["challenge:bulk"]
  /api/bulk-pairing/{id}/start-clocks:
    post:
      operationId: bulkPairingStartClocks
      summary: Manually start clocks
      description: |
        Immediately start all clocks of the games of a bulk pairing.

        This overrides the `startClocksAt` value of an existing bulk pairing.

        If the games have not yet been created (`bulk.pairAt` is in the future), then this does nothing.

        If the clocks have already started (`bulk.startClocksAt` is in the past), then this does nothing.
      tags:
        - Bulk pairings
      security:
        - OAuth2: ["challenge:bulk"]
  /api/bulk-pairing/{id}:
    get:
      operationId: bulkPairingGet
      summary: Show a bulk pairing
      description: |
        Get a single bulk pairing by its ID.
      tags:
        - Bulk pairings
      security:
        - OAuth2: ["challenge:bulk"]
    delete:
      operationId: bulkPairingDelete
      summary: Cancel a bulk pairing
      description: |
        Cancel and delete a bulk pairing that is scheduled in the future.

        If the games have already been created, then this does nothing.

        Canceling a bulk pairing does not refund the rate limit cost of that bulk pairing.
      tags:
        - Bulk pairings
      security:
        - OAuth2: ["challenge:bulk"]
  /api/round/{gameId}/add-time/{seconds}:
    post:
      operationId: roundAddTime
      summary: Add time to the opponent clock
      description: |
        Add seconds to the opponent's clock. Can be used to create games with time odds.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write"]
  /api/token/admin-challenge:
    post:
      operationId: adminChallengeTokens
      summary: Admin challenge tokens
      description: |
        **This endpoint can only be used by Lichess administrators. It will not work if you do not have the appropriate permissions.** Tournament organizers should instead use [OAuth](#tag/OAuth) to obtain `challenge:write` tokens from users in order to perform bulk pairing.*

        Create and obtain `challenge:write` tokens for multiple users.

        If a similar token already exists for a user, it is reused. This endpoint is idempotent.
      tags:
        - Challenges
      security:
        - OAuth2: ["web:mod"]
  /inbox/{username}:
    post:
      operationId: inboxUsername
      summary: Send a private message
      description: |
        Send a private message to another player.
      tags:
        - Messaging
      security:
        - OAuth2: ["msg:write"]
  /api/cloud-eval:
    get:
      operationId: apiCloudEval
      summary: Get cloud evaluation of a position.
      description: |
        Get the cached evaluation of a position, if available.

        Opening positions have more chances of being available. There are about 15 million positions in the database.

        Up to 5 variations may be available. Variants are supported.

        Use this endpoint to fetch a few positions here and there.
        If you want to download a lot of positions, [get the full list](https://database.lichess.org/#evals) from our exported database.
      tags:
        - Analysis
      security: []
  /api/external-engine:
    get:
      operationId: apiExternalEngineList
      summary: List external engines
      tags:
        - External engine
      security:
        - OAuth2: ["engine:read"]
      description: |
        Lists all external engines that have been registered for the user,
        and the credentials required to use them.
    post:
      operationId: apiExternalEngineCreate
      summary: Create external engine
      tags:
        - External engine
      security:
        - OAuth2: ["engine:write"]
      description: |
        Registers a new external engine for the user. It can then be selected
        and used on the analysis board.

        After registering, the provider should start waiting for analyis requests.
  /api/external-engine/{id}:
    get:
      operationId: apiExternalEngineGet
      summary: Get external engine
      tags:
        - External engine
      security:
        - OAuth2: ["engine:read"]
      description: |
        Get properties and credentials of an external engine.
    put:
      operationId: apiExternalEnginePut
      summary: Update external engine
      tags:
        - External engine
      security:
        - OAuth2: ["engine:write"]
      description: |
        Updates the properties of an external engine.
    delete:
      operationId: apiExternalEngineDelete
      summary: Delete external engine
      tags:
        - External engine
      security:
        - OAuth2: ["engine:write"]
      description: |
        Unregisters an external engine.
  /api/external-engine/{id}/analyse:
    servers:
      - url: https://engine.lichess.ovh
    post:
      operationId: apiExternalEngineAnalyse
      summary: Analyse with external engine
      tags:
        - External engine
      security: []
      description: |
        **Endpoint: `https://engine.lichess.ovh/api/external-engine/{id}/analyse`**

        Request analysis from an external engine.

        Response content is streamed as [newline delimited JSON](#section/Introduction/Streaming-with-ND-JSON).
        The properties are based on the [UCI specification](https://backscattering.de/chess/uci/#engine).
        Analysis stops when the client goes away, the requested limit
        is reached, or the provider goes away.
  /api/external-engine/work:
    servers:
      - url: https://engine.lichess.ovh
    post:
      operationId: apiExternalEngineAcquire
      summary: Acquire analysis request
      tags:
        - External engine
      security: []
      description: |
        **Endpoint: `https://engine.lichess.ovh/api/external-engine/work`**

        Wait for an analysis requests to any of the external engines that
        have been registered with the given `secret`.

        Uses long polling.

        After acquiring a request, the provider should immediately
        [start streaming the results](#tag/External-engine/operation/apiExternalEngineSubmit).
  /api/external-engine/work/{id}:
    servers:
      - url: https://engine.lichess.ovh
    post:
      operationId: apiExternalEngineSubmit
      summary: Answer analysis request
      tags:
        - External engine
      security: []
      description: |
        **Endpoint: `https://engine.lichess.ovh/api/external-engine/work/{id}`**

        Submit a stream of analysis as [UCI output](https://backscattering.de/chess/uci/#engine-info).

        * The engine should always be in `UCI_Chess960` mode.
        * `UCI_AnalyseMode` enabled if available.
        * It produces `info` with at least:
          - `depth`
          - `multipv` (between 1 and 5)
          - `score`
          - `nodes`
          - `time`
          - `pv`

        The server may close the connection at any time, indicating that
        the requester has gone away and analysis should be stopped.
  /oauth:
    get:
      operationId: oauth
      summary: Request authorization code
      tags:
        - OAuth
      security: []
      description: |
        OAuth2 authorization endpoint.

        Start the OAuth2 Authorization Code Flow with PKCE by securely
        generating two random strings unique to each authorization
        * `code_verifier`
        * `state`

        Store these in session storage. Make sure not to reveal `code_verifier`
        to eavesdroppers. Do not show it in URLs, do not abuse `state` to store
        it, do not send it over insecure connections. However it is fine if
        the user themselves can extract `code_verifier`, which will always be
        possible for fully client-side apps.

        Then send the user to this endpoint. They will be prompted to grant
        authorization and then be redirected back to the given `redirect_uri`.

        If the authorization failed, the following query string parameters will
        be appended to the redirection:
        * `error`, in particular with value `access_denied` if the user
           cancelled authorization
        * `error_description` to aid debugging
        * `state`, exactly as passed in the `state` parameter

        If the authorization succeeded, the following query string parameters
        will be appended to the redirection:
        * `code`, containing a fresh short-lived authorization code
        * `state`, exactly as passed in the `state` parameter

        Next, to defend against cross site request forgery, check that the
        returned `state` matches the `state` you originally generated.

        Finally, continue by using the authorization code to
        [obtain an access token](#operation/apiToken).
  /api/token:
    post:
      operationId: apiToken
      summary: Obtain access token
      tags:
        - OAuth
      security: []
      description: |
        OAuth2 token endpoint. Exchanges an authorization code for an access token.
    delete:
      operationId: apiTokenDelete
      summary: Revoke access token
      description: Revokes the access token sent as Bearer for this request.
      tags:
        - OAuth
      security:
        - OAuth2: []
  /api/token/test:
    post:
      operationId: tokenTest
      summary: Test multiple OAuth tokens
      description: |
        For up to 1000 OAuth tokens,
        returns their associated user ID and scopes,
        or `null` if the token is invalid.

        The method is `POST` so a longer list of tokens can be sent in the request body.
      tags:
        - OAuth
      security: []
  /masters:
    servers:
      - url: https://explorer.lichess.ovh
    get:
      operationId: openingExplorerMaster
      summary: Masters database
      description: |
        **Endpoint: <https://explorer.lichess.ovh/masters>**

        Example: `curl https://explorer.lichess.ovh/masters?play=d2d4,d7d5,c2c4,c7c6,c4d5`
      tags:
        - Opening Explorer
      security: []
  /lichess:
    servers:
      - url: https://explorer.lichess.ovh
    get:
      operationId: openingExplorerLichess
      summary: Lichess games
      description: |
        **Endpoint: <https://explorer.lichess.ovh/lichess>**

        Games sampled from all Lichess players.

        Example: `curl https://explorer.lichess.ovh/lichess?variant=standard&speeds=blitz,rapid,classical&ratings=2200,2500&fen=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201`
      tags:
        - Opening Explorer
      security: []
  /player:
    servers:
      - url: https://explorer.lichess.ovh
    get:
      operationId: openingExplorerPlayer
      summary: Player games
      description: |
        **Endpoint: <https://explorer.lichess.ovh/player>**

        Games of a Lichess player.

        Responds with a stream of [newline delimited JSON](#section/Introduction/Streaming-with-ND-JSON). Will start indexing
        on demand, immediately respond with the current results, and stream
        more updates until indexing is complete. The stream is throttled
        and deduplicated. Empty lines may be sent to avoid timeouts.

        Will index new games at most once per minute, and revisit previously
        ongoing games at most once every day.

        Example: `curl https://explorer.lichess.ovh/player?player=revoof&color=white&play=d2d4,d7d5&recentGames=1`
      tags:
        - Opening Explorer
      security: []
  /master/pgn/{gameId}:
    servers:
      - url: https://explorer.lichess.ovh
    get:
      operationId: openingExplorerMasterGame
      summary: OTB master game
      description: |
        **Endpoint: `https://explorer.lichess.ovh/masters/pgn/{gameId}`**

        Example: `curl https://explorer.lichess.ovh/masters/pgn/aAbqI4ey`
      tags:
        - Opening Explorer
      security: []
  /standard:
    servers:
      - url: https://tablebase.lichess.ovh
    get:
      operationId: tablebaseStandard
      summary: Tablebase lookup
      description: |
        **Endpoint: <https://tablebase.lichess.ovh>**

        Example: `curl http://tablebase.lichess.ovh/standard?fen=4k3/6KP/8/8/8/8/7p/8_w_-_-_0_1`
      tags:
        - Tablebase
      security: []
  /atomic:
    servers:
      - url: https://tablebase.lichess.ovh
    get:
      operationId: tablebaseAtomic
      summary: Tablebase lookup for Atomic chess
      description: |
        **Endpoint: <https://tablebase.lichess.ovh>**
      tags:
        - Tablebase
      security: []
  /antichess:
    servers:
      - url: https://tablebase.lichess.ovh
    get:
      operationId: antichessAtomic
      summary: Tablebase lookup for Antichess
      description: |
        **Endpoint: <https://tablebase.lichess.ovh>**
      tags:
        - Tablebase
      security: []
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: |
        Read [the introduction for how to make authenticated requests](#section/Introduction/Authentication).
      flows:
        authorizationCode:
          authorizationUrl: https://lichess.org/oauth
          tokenUrl: https://lichess.org/api/token
          scopes:
            "preference:read": Read your preferences
            "preference:write": Write your preferences
            "email:read": Read your email address
            "engine:read": Read your external engines
            "engine:write": Create, update, delete your external engines
            "challenge:read": Read incoming challenges
            "challenge:write": Create, accept, decline challenges
            "challenge:bulk": Create, delete, query bulk pairings
            "study:read": Read private studies and broadcasts
            "study:write": Create, update, delete studies and broadcasts
            "tournament:write": Create tournaments
            "racer:write": Create and join puzzle races
            "puzzle:read": Read puzzle activity
            "team:read": Read private team information
            "team:write": Join, leave teams
            "team:lead": Manage teams (kick members, send PMs)
            "follow:read": Read followed players
            "follow:write": Follow and unfollow other players
            "msg:write": Send private messages to other players
            "board:play": Play with the Board API
            "bot:play": Play with the Bot API. Only for [Bot accounts](#operation/botAccountUpgrade)
            "web:mod": Use moderator tools (within the bounds of your permissions)
