name: Publish

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  publish-to-npm:
    if: github.repository == 'lichess-org/api'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./types
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 26
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install --global pnpm@12
          pnpm install
      - run: pnpm gen
      - run: pnpm format
      - name: Check for changes
        id: check_changes
        run: |
          git status --porcelain
          echo "changed_files=$(git status --porcelain)" >> "$GITHUB_OUTPUT"
      - name: Publish to npm
        id: publish
        if: steps.check_changes.outputs.changed_files != ''
        run: |
          git add .
          npm version patch --no-git-tag-version
          version="$(node -p "require('./package.json').version")"
          sed -i 's/version: .*/version: '"$version"'/' ../doc/specs/lichess-api.yaml
          echo "version=$version" >> "$GITHUB_OUTPUT"
          npm publish --provenance
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        if: steps.check_changes.outputs.changed_files != ''
        with:
          commit_message: 'Release v${{ steps.publish.outputs.version }}'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
  publish-to-github-pages:
    if: github.repository == 'lichess-org/api'
    needs: publish-to-npm
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: doc
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: master
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          version: 12
          package_json_file: doc/package.json
      - run: pnpm install --frozen-lockfile
      - run: pnpm build --base=/api
      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0
      - uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: doc/dist
      - uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
        id: deployment
